### ISSUE TITLE
Save as HTML can't do GitHub Style

### ISSUE THREAD

**Issue by 9000-volts** [atom-community/markdown-preview-plus#112]
When saving as HTML, this package should insert the data-use-github-style attribute into the body element if the user has GitHub Style turned on.

Additionally, if you manually add data-use-github-style after exporting,  source code still appear as light-on-dark. This can be fixed by adding rules for a light style.

This can be very inconvenient for those that use the package for writing documents to be printed.

![demo-err-1](https://cloud.githubusercontent.com/assets/1672106/9825312/6918450e-58a0-11e5-9f49-9f21decb7250.png)
![demo-err-2](https://cloud.githubusercontent.com/assets/1672106/9825313/6918df64-58a0-11e5-9a71-10edf1f71e2f.png)

**Comment by Galadirith** [comment]
@htmlguy Thanks so much for your input, and sorry its taken me a couple of days to respond.

> When saving as HTML, this package should insert the data-use-github-style attribute into the body element if the user has GitHub Style turned on.

Your absolutely right this is the behaviour you would expect. We will probably implement this in a slightly different way, but the end result will still be the same, if GitHub style is turned on you save GitHub styled HTML :D

> source code still appear as light-on-dark. This can be fixed by adding rules for a light style.

So this is definitely possible. This minor issue is that unlike the styles for the rest of the converted markdown, GitHub don't appear to have open sourced their syntax colours so it would not be an exact replication of GitHub's style.

But as you suggested, using another light syntax theme would seem appropriate. My thought would be to use Atoms `atom-light-syntax` syntax theme when saving HTML. Would that work for you?

If you are interested, you can learn a bit more about the original origin of the GitHub styles option at https://github.com/atom/markdown-preview/issues/244 if you want.

**Comment by Galadirith** [comment]
For my reference on implementing this you can use:
````javascript
atom.packages.getLoadedPackage('atom-light-syntax').loadStylesheets()
atom.packages.getLoadedPackage('atom-light-syntax').stylesheets[0][1]
````
To grab `atom-light-syntax` compiled `.less` files. Dont use the [`reloadStylesheets()`](https://github.com/atom/atom/blob/38745761e2b67d613d7104808a5c8f50b0abf474/src/package.coffee#L403) method as that appears to also active the syntax theme.

**Comment by htmlguy** [comment]
I think `atom-light-syntax` would work well with the exported stylesheet.
You might, however, want to have a dropdown box in the settings for what syntax theme to use (but that would be an entirely different issue.)

**Comment by Galadirith** [comment]
> You might, however, want to have a dropdown box in the settings for what syntax theme to use

That's a good idea. I think if someone has already enabled GitHub styles then having a further selection might seem confusing, but within the constraints of not actually having the correct syntax colours this might well be the best option. But as you said that is for another issue :D Thanks @htmlguy

**Comment by mistycheney** [comment]
@9000-volts  "This can be fixed by adding rules for a light style." Can you elaborate how to do this? Thanks,
