### ISSUE TITLE
Move development into a dedicated develop branch

### ISSUE THREAD

**Issue by leipert** [atom-community/markdown-preview-plus#130]
I think we've reached the size where we should split the master branch into master and develop.

I do not know how familiar you are with the ominous git flow. But I think our development should look something like this:
1. we are developing on `feature/*`-branches that get merged into `develop` via Pull-Requests.
2. whoa we made so many awesome features, let's push a new minor (`2.X.0`) release. Therefore:
   1. Make PR from `develop` to `master`
   2. cool, all the CI tests work
   3. close all issues related to the new release
   4. Merge PR into `master`
   5. Release in tha :house: 
   6. generate a nice changelog
3. continuing nice developing on nice `feature/*`-branch. Dammit. There is a bug or a small fix like #123:
   1. Checkout `master`
   2. Create a `hotfix/*`-branch.
   3. Steps 2.ii-2.iv.
   4. Release `2.X.{1,...,∞}` patch release
   5. Merge `master` into `develop`.
   6. generate a nice changelog  

What do you think?

PS: Slightly related: [git up](https://github.com/msiemens/PyGitUp). A nice tool, executed by `git up` which stashes your local changes, pulls updates for all the branches and reapplies your changes :+1:

**Comment by Galadirith** [comment]
@leipert Are you talking about [Vincent Driessen's](http://nvie.com/posts/a-successful-git-branching-model/) model and his [git extension](https://github.com/nvie/gitflow)? I have seen it before and think this sounds like a great idea. I know a little while back you ran a hotfix which I assume you were trying to apply in a style like that workflow, but obviously the repo wasn't really set up for that.

I'll set that up for commit going forward on either Friday evening or Saturday morning, but if you did want to set it up before then, then please feel free to do so.

Thanks @leipert and I really hope everything's going well on your Thesis.

**Comment by Galadirith** [comment]
@leipert So sorry I didn't do this on the weekend (I realise it was basically only 3-4 clicks and types to add develop!).

I also removed [`2.1.x`](https://github.com/Galadirith/markdown-preview-plus/tree/2.1.x) which was all merged and no longer needed. There was just one point I wanted to make on the above:

> 3\. v\. Merge `master` into `develop`.

That's absolutely fine if this is the way you want to do it and I'd be happy to follow that convention. However if does differ from the [original post](http://nvie.com/posts/a-successful-git-branching-model/#creating-the-hotfix-branch) where the hotfix is merged directly into both `master` and `develop`.

Thanks @leipert.
