### ISSUE TITLE
Uncaught Syntax Error

### ISSUE THREAD

**Issue by sonv** [atom-community/markdown-preview-plus#148]
I am running Kubuntu 14.04 and was trying to get markdown-preview-plus to run. However, I keep getting this

Uncaught SyntaxError: unexpected : /opt/atom/resources/app.asar/node_modules/season/lib/cson.js:77

It wouldn't load Mathjax properly... Do you know what happens?

**Comment by lierdakil** [comment]
I know that it's been like 2 years, but FWIW, this would suggest that Atom installation is horrifyingly broken =\ Faulty HDD or RAM might be a reason for that, but there are multiple software reasons this might be happening as well. Reinstalling often helps with such problems. I will close as ETIMEDOUT.
