### ISSUE TITLE
Error becuse of MathJax trying to open image fonts

### ISSUE THREAD

**Issue by Kambis** [atom-community/markdown-preview-plus#162]
Sometimes equations are not rendered and I can see that it is because Mathjax trying to access image fonts which are not included. Adding the option **imageFont: ""**, in the configuration in mathjax-helper.cofee has fixed the problem for me.

**Comment by Galadirith** [comment]
@Kambis Thank you very much for the solution and I really apologise for taking so long to reply to you. Would you be able to provide an example of when this happens. Thanks again @Kambis.
