### ISSUE TITLE
Symlink issues

### ISSUE THREAD

**Issue by caspervonb** [atom-community/markdown-preview-plus#172]
If your package manager symlinks pandoc's location, homebrew is amongst the ones that do this.
You can't spawn a symlink with node, so passing a symlink fails silently. 

The fix is quite simple, just resolve with `realpath(1)`

``` sh
realpath $(which pandoc)
```

But an error should be thrown here? Also might want to note this in the docs, likely to bite novice mac users.

**Comment by lierdakil** [comment]
Is this still relevant? I'm pretty sure Node doesn't have any trouble with spawning symlinked binaries... At least it shouldn't fail *silently*...
