### ISSUE TITLE
latex limitations

### ISSUE THREAD

**Issue by Netsaver** [atom-community/markdown-preview-plus#180]
Hi, I'm using this extensions for the maintenance (via _atom_) of a wiki site with markdown enabled.
Most of $$ latex formulas (many many...) have a _/label_ for numbering and linking (via /eqref) all widespread the wiki.
MPP is very good for basic latex and styling, too.
Anyway I've been able to change internal mathjax folder with an other one downloaded from Mathjax website and nothing changed. No formula with /label inside is recognized.
Except for the first rendering of the page soon after atom startup, where also formulas with /label are displayed correctly. So I'ld like to know:
- is it possible to replace the mathjax folder with another mathjax local installation (e.g. giving somewhere the path), more complete?
- /label is not in the syntax limitations of the mathjax embedded in MPP, why it is not rendered?
- in particular, howto enable the /label instruction and possibly autonumbering?
  Thanks a lot for this plugin.
  Paul Netsaver, Rome

**Comment by dpo** [comment]
:+1: for equation numbers!

**Comment by Netsaver** [comment]
In particular (maybe I didn't explain properly), _on the first loading_, every markdown txt file with latex inside is displayed correctly, even formulas with _/label_ command (with no numbering but right display).
While editing the fiile, each time a formula is updated, that (only that one) is not rendered (the latex source is shown instead), while all other formulas keep the correct display.
After closing and reopening the _md-plus preview_ OR toggling the mathjax display, ALL latex formulas with _/label_ are no more rendered. The only way to have all them rendered is to restart Atom.
So, it would be wonderful having a latex environment with labels and numbering working, but anyway the main request would be having the /label command (and other commands which are not supported) simply **ignored**, continuing the latex processing).
Thanks, 
Paul Netsaver, Rome
