### ISSUE TITLE
Relative links within document not working

### ISSUE THREAD

**Issue by troypesola** [atom-community/markdown-preview-plus#182]
I've been trying to use relative links within a markdown document, but the preview doesn't respond.

In one section of the file I have`[test](#test)`

Then further down I code it manually in html to ensure the target is defined

`<h3 id="test">testing</h3>`

But the preview doesn't respond to clicking the link.

I use kramdown (through a faked pandoc batch file) and it supports footnotes and table of contents.  The generated HTML is correct, but the preview isn't handling relative links in the simple test, nor in the full kramdown generated output.

Any suggestions would be greatly appreciated.

**Comment by Zelin-Feng** [comment]
Have you got any method to solve it by far? I'm using pandoc as parser and having the same problem :(

**Comment by tvld** [comment]
+1 I just installed this in hopes of having it fized as the orginal has this problem too.. in fail.

**Comment by troypesola** [comment]
I'm reverted back to using Marked2App with a kramdown custom processor for most things.  that works well, with the exception of relative links within a PDF export.  progress in some areas.

**Comment by rriemann** [comment]
It is the same for footnotes. They also do not allow navigation in the preview pane.

**Comment by lierdakil** [comment]
I'll close this in favor of #303
