### ISSUE TITLE
SVG Parsing

### ISSUE THREAD

**Issue by dmckean** [atom-community/markdown-preview-plus#183]
htmlparser2 has difficulting parsing SVG self-closing tags, is it possible to load cheerio with `xmlMode: true` just for SVG tags?

https://github.com/fb55/htmlparser2/issues/79

Ex.

``` html
<html>
  <body>
      <svg width="200pt" height="200pt" viewBox="0.00 0.00 400 400">
          <g>
              <polygon fill="red" stroke="none" points="0,0 0,200 200,200 200,0 0,0"/>
              <ellipse fill="none" stroke="black" stroke-width=10 cx="100" cy="100" rx="50" ry="50"/>
          </g>
      </svg>
  </body>
</html>
```

Renders as 

``` html
<html>
  <body>
    <svg width="200pt" height="200pt" viewbox="0.00 0.00 400 400">
      <g>
        <polygon fill="red" stroke="none" points="0,0 0,200 200,200 200,0 0,0">
          <ellipse fill="none" stroke="black" stroke-width="10" cx="100" cy="100" rx="50" ry="50"></ellipse>
        </polygon>
      </g>
    </svg>
  </body>
</html>
```

**Comment by Galadirith** [comment]
@dmckean Thanks for opening the issue and I really apologise for taking so long to respond. 

I must admit I am confused. We don't use either `htmlparser2` or `cheerio` and I am not entirely sure what your are trying to achieve. Do you have a markdown document which has raw `svg` tags in it that you would like to render as a preview inside atom?

If you could provide some more details on this issue I would be very glad to help. Thanks again.

**Comment by dmckean** [comment]
@Galadirith yes, the markdown document has svg tags. I'm actually using a pandoc filter (similar to [this](https://gitlab.com/meonkeys/pandoc-dot-svg-hack/blob/master/graphviz.py)) to generate the svg from a markdown code block.

I think that MMP has used `cheerio` since 8e0f10c669ed159867157d07f1348a5983938439 for html sanitizing. I'd have to take another look, but it was one of the the `cheerio.load(html)` calls, most probably the one for `tokenizeCodeBlocks` at 145 of of [renderer.cofee](https://github.com/Galadirith/markdown-preview-plus/blob/f1984a24f882d4f747f643ba8d75fd672122988d/lib/renderer.coffee#L145) .

If you'd like I can work on a pull request, but it seems that passing `xmlMode: true` to the cheerio parser would eventually make it's way to `htmlparser2`, which might be enough to fix the problem without breaking something else if that `load` call is only used on SVG tags.

Cheerio's `load` ([static.js](https://github.com/cheeriojs/cheerio/blob/d0551dc41c3a733d6599d426afda5e949787e07b/lib/static.js)) calls their `parse` ([parse.js](https://github.com/cheeriojs/cheerio/blob/d0551dc41c3a733d6599d426afda5e949787e07b/lib/parse.js))  which uses `htmlparer2`'s `parseDOM` ([index.js](https://github.com/fb55/htmlparser2/blob/9770f247038bf953efbb4b7621f6ae3de90aeaae/lib/index.js))  to construct a `Parser` object ([Parser.js](https://github.com/fb55/htmlparser2/blob/9770f247038bf953efbb4b7621f6ae3de90aeaae/lib/Parser.js)) for parsing HTML. The trouble is that SVG is really derived from XML. I can't remember the exact reason why `htmlparser2` has trouble with self-closing tags but it's either because they are not a part of HTML5 or because SVG's self-closing tags don't exist in the HTML4's list of self-closing tags.

**Comment by lierdakil** [comment]
Closing as irrelevant, since we've got rid of `cheerio` in favour of just using Chrome's DOM parsing capabilities.
