### ISSUE TITLE
A Message to Markdown Preview Plus Users

### ISSUE THREAD

**Issue by Galadirith** [atom-community/markdown-preview-plus#188]
### Thank you for continuing to use MPP

Hi everyone,

Thank you so much for the time you've all taken to submit issues and PR's over the last few months. I really apologise for being absent for so long and I will be responding to all the open issues and PR's over the next few weeks.

I no longer have the time to dedicate to actively develop MPP. This means that I will not be able to add new features that I had previous planned too and were listed on upcoming milestones.

However I will be restarting the maintenance of MPP which extends to fixing bugs, and merging in upstream changes from [`markdown-preview`](https://github.com/atom/markdown-preview). If anyone would like to see a feature added to MPP I would be really happy to discuss and merge PR's. And if you would like to open a PR but are not sure where to start please get in contact and I would be very happy to talk about where to begin.

@Galadirith

**Comment by Galadirith** [comment]
@9000-volts, @AddemF, @Aeon512, @Agnishom, @Bromgard, @EliasGabrielsson, @EntilZha, @Galadirith, @Hufschmidt, @JacobIsrael123, @Jamesits, @KCErb, @Kambis, @Kkevsterrr, @MAccadia, @MatteoRagni, @Netsaver, @NobbZ, @OJFord, @alerque, @alexellis, @appanp, @branden-akana, @breschke, @bsandrow, @caspervonb, @catscarlet, @cavaunpeu, @chrahunt, @clbarnes, @dgoppenheimer, @dmckean, @dpo, @dsernst, @duppypro, @durianskh, @edwinksl, @eljuanchosf, @g0ne, @gitkrax, @gudh, @hanhua, @hanwentao, @happydemic, @harper357, @jcpsantiago, @jiku, @jneubrand, @jojje, @jonand, @josephcc, @jronallo, @kleinbottle, @kurtharriger, @laokaplow, @leipert, @levantis, @lierdakil, @liufuyang, @mangecoeur, @mengzdsd, @mmstick, @nmoehrle, @nobol, @oliche, @ondine, @oztalha, @philomonk, @polarathene, @remi-gelinas, @richardwthompson, @rriemann, @scordeiro, @sengopal, @sitdisch, @sonv, @spye, @stasberkov, @szhorvat, @t-knapp, @teoric, @thomasingalls, @timlyo, @torsday, @trickyEdecay, @troypesola, @tylergraf, @xHN35RQ

**Comment by Galadirith** [comment]
@harper357, @jcpsantiago, @jiku, @jneubrand, @jojje, @jonand, @josephcc, @jronallo, @kleinbottle, @kurtharriger, @laokaplow, @leipert, @levantis, @lierdakil, @liufuyang, @mangecoeur, @mengzdsd, @mmstick, @nmoehrle, @nobol, @oliche, @ondine, @oztalha, @philomonk, @polarathene, @remi-gelinas, @richardwthompson, @rriemann, @scordeiro, @sengopal, @sitdisch, @sonv, @spye, @stasberkov, @szhorvat, @t-knapp, @teoric, @thomasingalls, @timlyo, @torsday, @trickyEdecay, @troypesola, @tylergraf, @xHN35RQ

**Comment by lierdakil** [comment]
You could transfer package ownership to [atom-community](https://github.com/atom-community), which would, at least in theory, keep this rolling even if you go MIA. Try contacting [one of the members](https://github.com/orgs/atom-community/people) if this is something you would be interested in.

**Comment by Galadirith** [comment]
@lierdakil Thanks for the suggestion. I think thats a really wise idea, I'll try contacting one of the members.

**Comment by mangecoeur** [comment]
sad to hear you don't have time, this is a great package. Hopefully you can transfer ownership to the atom-community, then maybe add a couple of folks as maintainers.

**Comment by vjpr** [comment]
Thanks for your efforts - a really great package! It might be an idea to make a note of this in the README.

**Comment by philomonk** [comment]
Thank you for all the work you put in! Personally, I see even greater need
for a package like this in the future. I'm currently working to anchor the
training of Academic Markdown and Pandoc at my university and with that
come licensing limitations. That means that I can only train people using
Atom instead of the, as I see it, more common Sublime Text 3. Also, this
package is an important part in overcoming the need for the command line
which is the primary obstacle for many scholars to adopt the
Markdown-Pandoc set-up.

Vaughan Rouesnel <notifications@github.com> schrieb am Di., 19. Apr. 2016,
08:52:
