### ISSUE TITLE
Support hiding YAML front matter

### ISSUE THREAD

**Issue by chrahunt** [atom-community/markdown-preview-plus#199]
When writing pages/posts for Jekyll, often it's necessary to set some metadata in a YAML front matter section preceding the page/post content. As an example:

![image](https://cloud.githubusercontent.com/assets/2312275/14234907/c6efef0c-f9bc-11e5-9f22-6df882c0481b.png)

which gets rendered in the preview panel as

![image](https://cloud.githubusercontent.com/assets/2312275/14234909/d9838b9c-f9bc-11e5-9482-0ec693a243a4.png)

If there was a toggleable option to hide leading sections when surrounded by `---` it would make the preview panel a little prettier when using Atom/mpp for this purpose. Let me know what you think.

**Comment by Geotig** [comment]
You can use pandoc to generate the html from markdown, and it supports YAML blocks that it doesn't render in the preview pane. Give it a try, I havent seen a performance drop in my work or home computers.

**Comment by mgerzabek** [comment]
It works! 
Go to Settings > Packages
Search for markdown-preview-plus
Scroll down the settings until you find „Enable Pandoc Parser“ and check it.
Voilá, now the front-matter is gone.
Awesome 👍

**Comment by lierdakil** [comment]
YAML front-matter support added to markdown-it parser in v4.3.0 via [markdown-it-front-matter](https://www.npmjs.com/package/markdown-it-front-matter)
