### ISSUE TITLE
Preview MathJax Crash

### ISSUE THREAD

**Issue by teok** [atom-community/markdown-preview-plus#200]
Hi,

I installed MPP for Atom in Windows 10 and preview with `ctrl-shift-x` doesn't work. So I checked _Enable Math Rendering By Default_ and if I press `ctr+shift+m` Atom show math preview but it crash.
Can you help me?

Matteo

**Comment by escrowdis** [comment]
Got the same problem. Type `Ctrl+Shift+x` didn't work on Windows 10. Have no idea how to preview math functino@@

**Comment by lierdakil** [comment]
Crash report could be helpful, if you have one.

**Comment by escrowdis** [comment]
@lierdakil actually there's no crash report, just nothing happen to this combo.

**Comment by lierdakil** [comment]
Maybe something steals it? Try running 'Markdown Preview Plus: Toggle Render Latex' command from command pallette. Also make sure core markdown-preview package is disabled:
![image](https://user-images.githubusercontent.com/7275622/28430121-f9efef16-6d87-11e7-887c-917cd196c582.png)

**Comment by escrowdis** [comment]
@lierdakil I've done that before and still not work

**Comment by lierdakil** [comment]
Closing due to age. Can't do anything if there's no information about what's going wrong.
