### ISSUE TITLE
Ctrl+Shift+m doesn't work

### ISSUE THREAD

**Issue by hannwong** [atom-community/markdown-preview-plus#206]
Not on Mac + Chrome.

Nothing happens when I press those keys.

**Comment by chrahunt** [comment]
See instructions [here](http://stackoverflow.com/questions/24885276/how-can-i-find-out-the-keyboard-shortcut-assignments-in-the-atom-text-editor) for viewing the keybindings currently set in Atom. The one you're looking for has the Command `markdown-preview-plus:toggle`. Whatever is present in the "Keystroke" column is what you would press to invoke the command. Report back if it is present (and nothing else is present with that keyboard shortcut) but still not working when you try the key combination when viewing a document.

**Comment by hannwong** [comment]
I'm so sorry! This issue is invalid.

In Chrome, I had to go to *Settings* > *Extensions*, and get *Markdown Preview Plus* to ``Allow access to file URLs``.

**Comment by chrahunt** [comment]
No problem, just make sure to close the issue!
