### ISSUE TITLE
When `Scroll Past End` is set, code block in preview captures mouse which interferes with scrolling

### ISSUE THREAD

**Issue by vjpr** [atom-community/markdown-preview-plus#209]
When I write a code block. When I scroll the preview panel, the scroll view captures my mouse scrolling which makes it tricky to scroll the page.

It also appears with a white background that does not look like Github.com.

**Comment by vjpr** [comment]
So it turns out that the code block is actually an entire `atom-text-editor` (that's really cool), and when `Scroll Past End` is set in the settings it causes this behaviour.

`Scroll Past End` should always be disabled in preview.

**Comment by vjpr** [comment]
https://github.com/atom/markdown-preview/issues/209

**Comment by lierdakil** [comment]
I believe this was fixed at some point, open new issue if not.
