### ISSUE TITLE
Could raw_tex and  tex_math_double_backslash please be supported?

### ISSUE THREAD

**Issue by alves** [atom-community/markdown-preview-plus#214]
Hi,
The raw_tex and tex_math_double_backslash extensions do not work with PDF output (was already documented for HTML output). Since I work on rmarkdown files to be knitted into an MD in R [actually another MPP feature that would be extremely useful!], it would be useful if MPP could harmonise its treatment of TeX/LaTeX code with pandoc (i.e. support extensions raw_tex tex_math_double_backslash) and thus treat TeX code as determined by extensions chosen instead as the MPP internal way of handling math code.
Many thanks for letting me know if this feature will be supported as some point.
Kind regards,
Ivan

**Comment by lierdakil** [comment]
Not sure I understand the request correctly, but long and short of it is: use Pandoc.
