### ISSUE TITLE
Github flavored Markdown

### ISSUE THREAD

**Issue by abhi18av** [atom-community/markdown-preview-plus#219]
Hey, for some reason the package fails to initiate when the language is set to Github flavored Markdown. I'm using this with the nvatom package.

https://atom.io/packages/nvatom

Otherwise, this package has been an absolute blessing. Thanks for making this package

**Comment by danamkaplan** [comment]
I had the same issue. Check to see if you disabled the built-in Markdown Package first. That solved it for me.

**Comment by abhi18av** [comment]
@danamkaplan Yup, solved it too a while back but forgot to close this.
