### ISSUE TITLE
files with txt and md extension created outside atom not previewing

### ISSUE THREAD

**Issue by rsshel** [atom-community/markdown-preview-plus#221]
Great package that I use constantly.  After the latest update any files I create with a .txt or .md extension outside of Atom are not previewed by MPP.  Even some older files created in Atom are not previewing at all.  Toggling MPP results in nothing.  If I remove the .md or .txt extension from the file, all works as it should.  This is all on a Macbook air.  Have not tried it on linux.  Thanks!

**Comment by pierregodard** [comment]
Do you use `nvatom` ? i can reproduce it with a markdown file set to `nvAtom Github Markdown` grammar (`source.gfm.nvatom` scope) which is going to be the case under your `nvatom` note directory as far as i understand it. If you change the scope to `source.gfm` (with eg. `Pandoc Markdown` grammar from the `language-pfm` package, or the default `language-gfm` package), MPP will likely work again.

If that's the case, you might want to add `source.gfm.nvatom` to the grammar list in MPP's settings (required an `Atom` restart for me).

**Comment by rsshel** [comment]
Thank you.  I do use nvatom.  i'll try your suggestion and let you know.
Thanks for the fast response!

R

Robert Shelton

**Comment by rsshel** [comment]
That solved it.  Thanks again.  Great package, by the way.

Robert Shelton
