### ISSUE TITLE
'Break On Single New Line' option broken?

### ISSUE THREAD

**Issue by pierregodard** [atom-community/markdown-preview-plus#222]
`Break On Single New Line` works as expected with the `markdown-preview` core package's equivalent option. But with `markdown-preview-plus` (`2.4.0` with Atom `1.9.8` on OS X `10.11.6`) it seems broken.

**Comment by lierdakil** [comment]
Please note that this option doesn't work with pandoc renderer. If this happens with default options, then this might be Mac-specific, since it works as expected on Linux.
I personally can't investigate this, but anyone willing is more than welcome to.

**Comment by Galadirith** [comment]
@lierdakil Thanks for checking on Linux.

@pierregodard @geekck I'm really sorry your getting this issue. I have tested that this does work on Mac (MPP@2.4.1, OSX@10.11.6, Atom@1.13.1) for the default render (The specific line that handles this feature is [`lib/markdown-it-helper.coffee#L29`](https://github.com/Galadirith/markdown-preview-plus/blob/f1984a24f882d4f747f643ba8d75fd672122988d/lib/markdown-it-helper.coffee#L29))

![222-break-on-newline](https://cloud.githubusercontent.com/assets/1201875/22458322/db76e12c-e793-11e6-98be-88d951daf185.gif)

You should be able to get it to work with Pandoc by setting the appropriate `hard_line_breaks` flag (See the [Formats](general-options) and [Non-pandoc extensions](http://pandoc.org/MANUAL.html#non-pandoc-extensions) of the Pandoc manual)

![screen shot 2017-01-31 at 09 16 52](https://cloud.githubusercontent.com/assets/1201875/22458834/2c4f8764-e796-11e6-9411-140ce4b57438.png)

Please let us know if that works. Thanks :smile:

**Comment by pierregodard** [comment]
@lierdakil i was indeed using the pandoc renderer. The default renderer works as expected w.r.t the option `Break On Single New Line`.

@Galadirith thank you so much, the `hard_line_breaks` flag does the trick! 
(incidentally, i was also very happy to find the flag `lists_without_preceding_blankline` in the link you provided:)

thank you both very much!!!

**Comment by lierdakil** [comment]
So, as far as I can tell, this issue is resolved, but this should be mentioned in README. Correct me if I'm wrong.
