### ISSUE TITLE
enabling pandoc freezes/crashes atom

### ISSUE THREAD

**Issue by stefanprobst** [atom-community/markdown-preview-plus#224]
Hi, when I enable pandoc citation support in MPP, and toggle preview, atom (1.9.9) freezes and then pops up dialog "editor is not responding". When pressing Keep waiting, the Editor has crashed dialog pops up.

Interestingly, the debug console doesn't show any messages.

**Comment by AshleyByeUK** [comment]
I'm having this same problem in Atom 1.10.2.

**Comment by AshleyByeUK** [comment]
I just found [this](https://github.com/Galadirith/markdown-preview-plus/issues/50), which solves the problem - use the fallback options. Could the brief docs be updated to reflect this is the purpose of fallback?
