### ISSUE TITLE
Support for LaTeX's pseudo code

### ISSUE THREAD

**Issue by MRBeussink** [atom-community/markdown-preview-plus#225]
I am using this for a university course on algorithms, and I am having trouble getting LaTeX algorithms to work.  I'm guessing that this only currently supports LaTeX math and not LaTeX algorithms.  Is that the case, or am I just giving it the wrong input?

**Comment by lierdakil** [comment]
Arbitrary LaTeX is not supported. Only math is, and that's mostly because Pandoc does that. Won't implement support for arbitrary LaTeX either, since it's wildly out of scope.

Sorry nobody answered sooner.
