### ISSUE TITLE
cntl-shift-M not toggle preview window

### ISSUE THREAD

**Issue by diazgilberto** [atom-community/markdown-preview-plus#226]
I'm running Atom 1.10.0. For some reason the keybinding is not toggling the preview window. I `cmd+.` to double check the keybinding were correct, and it is. What might be wrong?

**Comment by Krillian111** [comment]
I had the same issues and (in my case) it was caused by the fact that the core package "markdown-preview" (the basic version) had its preview mapped to the same hotkey. I resolved it by disabling the core package and only using markdown-preview-plus.
