### ISSUE TITLE
Pandora Syntax highlighting

### ISSUE THREAD

**Issue by xelatihy** [atom-community/markdown-preview-plus#230]
Pandora syntax highlighting is not visible in the preview. Looking at the HTML, pandoc code classes are not there, so it seems that pandoc did not enable syntax highlighting, which is on by default in my build.

Is there a workaround?

**Comment by aryamanarora** [comment]
I have this issue too...

**Comment by lierdakil** [comment]
Syntax highlighting in preview is handled by Atom grammars. Install a suitable grammar package. Alternatively, there's an option to use Pandoc's native code block styles.
