### ISSUE TITLE
pandoc exited with code 83: pandoc-crossref

### ISSUE THREAD

**Issue by Kumassy** [atom-community/markdown-preview-plus#238]
I'm writing some reports on chemistry, but I've got an error. I guess this part may cause a crash. This is an excerpt from my reports:

```

---
header-includes:
  - \usepackage[version=3]{mhchem}
  - \usepackage{chemfig}

---

\resizebox{\textwidth}{!}{
  \chemfig{*6((-R2)=( - R3)-(-[,1.0001] O -[::60]?(-[6]) -[:-30] -[::60] -[:-30] -[::60] (-[2]) -[:-30] -[::60] -[:-30] -[::60](-[2]) -[:-30] -[::60] -[:-30] -[::60](-[2]) -[:-30])=(-[,1.0001] -[:-30] -[6]?)-( - R1)=( - OH)-)} %*
}

```

This code still gives an error: `pandoc exited with code 83: pandoc-crossref: Error in $[1][3][27]: When expecting a product of 3 values, encountered an Array of 2 elements instead`
<img width="510" alt="2016-10-23 00 57 11" src="https://cloud.githubusercontent.com/assets/6278784/19620594/d89c2f9c-98bb-11e6-8ab5-d592855caea8.png">

But I can compile the code above via commandline with no error messages:`pandoc  donotwork.md -o out.pdf -V documentclass=ltjsarticle --latex-engine=lualatex -N`
Why?

Here is my setting of MPP:
<img width="757" alt="2016-10-23 00 44 30" src="https://cloud.githubusercontent.com/assets/6278784/19620559/25a150e8-98bb-11e6-95b3-e452df5cb3b6.png">

MPP version: 2.4.0  
pandoc version: 1.17.2 (Compiled with texmath 0.8.6.5, highlighting-kate 0.6.3.)  
Atom version: 1.11.1  
OS: OS X 10.11.6 El Captain

**Comment by Kumassy** [comment]
When I restarted Atom, MPP did'nt give an error. This is the view of MPP:

<img width="611" alt="2016-10-23 01 34 40" src="https://cloud.githubusercontent.com/assets/6278784/19620879/e53116b4-98c0-11e6-9e9c-9c64ce8e1427.png">

**Comment by Kumassy** [comment]
The same crash happened again.  But MPP didn't crash when I comment out the suspicious codes. `\resizebox{\textwidth}{!}{
  \chemfig{*6((-R2)=( - R3)-(-[,1.0001] O -[::60]?(-[6]) -[:-30] -[::60] -[:-30] -[::60] (-[2]) -[:-30] -[::60] -[:-30] -[::60](-[2]) -[:-30] -[::60] -[:-30] -[::60](-[2]) -[:-30])=(-[,1.0001] -[:-30] -[6]?)-( - R1)=( - OH)-)} %*
}`

I don't know what exactly causes the crash, but I guess some LaTeX environment or macros are harmful to MPP.

Why don't we provide an option to skip parsing some codes inside specific LaTeX environment or macros?

**Comment by lierdakil** [comment]
Short version: this is the issue with pandoc-crossref filter, and it seems that pandoc-crossref version you're using is incompatible with pandoc version you're using. As an author of pandoc-crossref filter, I would guess that you're (were?) using pandoc v1.16, which is not supported by pandoc-crossref since 0.2.2.1 (Jul 2016). If you built pandoc-crossref from source, make sure *both* pandoc and pandoc-crossref that were built are in PATH. If you used prebuilt binary, make sure your pandoc version corresponds to one that pandoc-crossref was built with.
