### ISSUE TITLE
Images don't work

### ISSUE THREAD

**Issue by mickley** [atom-community/markdown-preview-plus#240]
First of all, it looks like MPP is sending the file via stdout instead of as a filename argument to pandoc.  This is problematic for a ton of reasons because there's no way for pandoc (or any preprocessor) to know where the file was originally.  So all relative links to images, or any other files like .bib, .csl, .csv, etc. will be broken!

Secondly, even when the full path to an image (eg png) is specified, it's still not displayed in the preview pane.

**Comment by ryanmeisters** [comment]
I think images do work. I thought they didn't, but I had the wrong path to my image. The following works for me (displays in the preview): 

`![An Image](relative/path/to/image.png)`

**Comment by stsewd** [comment]
Check if your path contain spaces, may related to #187. You should use `![image](<path/with spaces/my file.png>)`
