### ISSUE TITLE
Allow custom pandoc command for complex project with multiple files 

### ISSUE THREAD

**Issue by stakaz** [atom-community/markdown-preview-plus#243]
Hello, it would be great to have an option to choose a list of files which have to be used by pandoc to produce the output in the preview. I have a project with multiple documents, e.g. metadata.md chapter1.md chapter2.md.
What I want to see in the preview is the output of the command like:

`pandoc metadata.md chapter1.md chapter2.md -o something.html`

The important thing is to be able to use multiple files at the same time.
Principally, it is ok to have only one document previewed at a time BUT when e.g. using own LaTeX new commands for math input, I would need to copy them to each file separately, which is not a suitable solution  (I have about 200 of them). Also the metadata file which contains all settings for the whole project must be copied into each file.

Just a short tick with something like "use this command for generating the preview" (and neglect the current document) would be great for such using case.

Thanks

**Comment by lierdakil** [comment]
Yeah... sorry, this is not happening, since it's wildly out of scope. See [documentation on user-defined macros](https://github.com/atom-community/markdown-preview-plus/blob/master/docs/math.md#macros) for information on how to define MathJax macros globally.
