### ISSUE TITLE
Support for Github emojis

### ISSUE THREAD

**Issue by Evpok** [atom-community/markdown-preview-plus#244]
I couldn't find a mention of emoji support and there seem to be none, which is a bit of a disappointment coming from core markdown-preview. Are emojis supported by this package (in which case this is a bug report) or not (in which case this is a feature request) ?

**Comment by leipert** [comment]
@Evpok Do you render with pandoc or markdown-it?

If you run the latter, this could easily be implemented with the help of this:
https://github.com/markdown-it/markdown-it-emoji

**Comment by Evpok** [comment]
I don't use pandoc, so that would work for me. Is the pandoc emoji extension enabled btw ? That could be a workaround.

**Comment by lierdakil** [comment]
@Evpok, you can enable it. Change 'Pandoc Options: Markdown Flavor' to `markdown+emoji`.

**Comment by lierdakil** [comment]
For reference, `markdown-preview` uses [emoji-images](https://www.npmjs.com/package/emoji-images) (apparently via `roster`, [here](https://github.com/gjtorikian/roaster/blob/master/src/roaster.coffee#L29))

So using twemoji, as markdown-it-emoji suggests, would be somewhat weird, i.e. compare and contrast:
- GitHub emojis: 
🎉 😜 👯 🍻 🎈 🎤 🎮 🚀 🌉 ✨
- Twitter emojis: 
![image](https://cloud.githubusercontent.com/assets/7275622/23679014/63e43b58-0397-11e7-97c7-7777e64e9a67.png)

Of course, we can use emoji-images instead.

**Comment by pilarArr** [comment]
@lierdakil Thank you for your tip, this got it working. Maybe you could add some little todo list on how to activate this emoji support somewhere in the features.

**Comment by lierdakil** [comment]
https://github.com/atom-community/markdown-preview-plus/pull/332, although I ultimately opted for using twitter's emoji because those can be easily used offline without any licensing concerns. With GitHub, my best bet would be pulling those images from GitHub's CDN basically, which is not ideal -- I don't think I could repackage those since licensing terms are unclear.
