### ISSUE TITLE
"ctrl+shift+x" doesn't work

### ISSUE THREAD

**Issue by BetaMatrix** [atom-community/markdown-preview-plus#246]
Even the keybindings was added into your keymap file
OS:Fedora 25
GNOME  Version 3.22.1
Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by Artillect** [comment]
I'm getting the same issue
Atom: 1.13.1
Windows 10: KB3216755
Chrome: 55.0.2883.87

**Comment by lierdakil** [comment]
Check if something else steals it. Run `Key Binding Resolver: Toggle` command from command pallette (or `ctrl`+`.`), then try `ctrl`+`shift`+`x` to see what command actually gets executed in the panel at the bottom.

**Comment by lierdakil** [comment]
ETIMEDOUT, closing.
