### ISSUE TITLE
Equation numbering and referencing

### ISSUE THREAD

**Issue by indigo4x** [atom-community/markdown-preview-plus#255]
Hi,

I'm quite new to Atom and currently writing proposals involving large amount of math expressions. This package is amazing!

I'm trying to number my equations and reference them back in the paper when necessary. Seems the numbering does not work. I've found a previous issue regarding on this:

https://github.com/Galadirith/markdown-preview-plus/issues/8

I've made the corresponding changes as stated in the link above but it did not work (cause the whole MPP broken down...) Seems some of the coding has changed also, as compared to the link above.

May I know if there's a way to number the equations in the current version? And if possible, could I reference them back in the paragraph with something like, \ref{eq:1}?

Many thanks in advance.

**Comment by lierdakil** [comment]
Numbering and especially referencing won't work with the preview the way you want to. That said, you could try using pandoc renderer with [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) filter. The filter will handle numbering and referencing for you. Bear in mind pandoc renderer can be slow.

You need to install [pandoc](http://pandoc.org/) and [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) (see releases, there are prebuilt binaries there)

Something like this in settings should work:
![image](https://cloud.githubusercontent.com/assets/7275622/22453798/8cc79acc-e792-11e6-8e15-e1ac3ea25639.png)


Make sure you have pandoc and pandoc-crossref on PATH (or specify full path to executables), and that 'Pandoc Options: Citations' is disabled (this will mess with pandoc-crossref -- if you want citations, add `,--fitler=pandoc-citeproc` after `--filter=pandoc-crossref` manually)

**Comment by kikunota** [comment]
Thank you, lierdakil.
Pandoc-crossref works on windows 7.  Is there anyways to use pandoc-citeproc and pandoc-crossref at the same time in Atom. Or is post-processing the file only solution at the moment.

**Comment by lierdakil** [comment]
As I was saying,
> if you want citations, add ,--fitler=pandoc-citeproc after --filter=pandoc-crossref manually

i.e. commandline arguments should look something like this:
```
--filter=pandoc-crossref, --filter=pandoc-citeproc
```

**Comment by kikunota** [comment]
I followed your advice and made a batch file that compiles markdown file and opens compiled html file. I also assigned hot-key to trigger the batch file whenever needed. It is not a real-time rendering of the markdown file but this works for now. Thank you for the help.

**Comment by lierdakil** [comment]
@kikunota, I didn't at any point suggest to create a batch file, at least I don't think I did. You can configure Pandoc's arguments from MPP settings, and that will work just fine. Do avoid enabling `Pandoc Options: Citations` though, since it adds `--fitler=pandoc-citeproc` *before* other arguments, which would be a problem.

**Comment by kikunota** [comment]
Sorry I misinterpreted. You didn't mention about batch file. But I did end up making a batch file since I wanted to compile with a hot-key while using Atom. (Is that a bad idea?) Anyways, thank you for the great packages (pandoc-crossref and this)

**Comment by lierdakil** [comment]
It's not a *bad* idea. But as you said, it's not "real-time" rendering. So if you want it to be "real-time", you'll need to go through MPP. Of course, if you're content with the setup you've got right now, you don't need to change anything ^^

**Comment by masonlr** [comment]
If `Pandoc Options: Citations` is disabled, then the `.bib` file set in Bibliography or Fallback Bibliography doesn't seem to be located. Is there a method for using say

```
--filter=pandoc-crossref, --filter=pandoc-citeproc, --bibliography=bibliography.bib
```

such that the path relative to the active markdown file is used when searching for the `bibliography.bib` file?

**Comment by lierdakil** [comment]
@masonlr, this is a bug =\ #271 should fix that, hopefully.

**Comment by masonlr** [comment]
Thanks, can confirm that this is working.

**Comment by lierdakil** [comment]
Okay, released with v2.4.5.

**Comment by Datseris** [comment]
If you only care about equation you can also simply use [`pandoc-eqnos`](https://github.com/tomduck/pandoc-eqnos), works perfectly for me.

**Comment by i2000s** [comment]
@Datseris I don't know if this is related, but when I have `\label{somename}` to label my equations and use `pandoc-eqnos` filter to rerender the equation with double `ctrl+shift+x`, then the preview doesn't show the rendered equations. Only the latex code of the equations is showing.

Can you confirm if you see this issue and how to fix this numbering and referencing problem? Thanks.
