### ISSUE TITLE
pandoc mermaid filter doesn't work as expected

### ISSUE THREAD

**Issue by pareyesv** [atom-community/markdown-preview-plus#268]
I'm using pandoc (_Enable Pandoc Parser_ is ON) with the mermaid filter. In _Pandoc Options: Command Line Arguments_:

```
--standalone, --smart, --filter=pandoc-citeproc, --filter=mermaid-filter
```

If I write a file `test.md` with the following mermaid code (pandoc style)

    ```mermaid
    
    graph LR
        a-->b
        c-->d
    ```

the image is not shown in the preview.

However, if I run pandoc from console (same dir):

```
pandoc --standalone --smart -o test.html --filter pandoc-citeproc --filter mermaid-filter test.md
```

then the preview (markdown-preview-plus) shows the image as expected.

**Comment by lierdakil** [comment]
Can't test since mermaid-filter refuses to work for me. Please post output HTML (right click on preview -> copy as html), preferably via gist (or pastebin or whatever)

**Comment by pareyesv** [comment]
[Here](https://gist.github.com/pareyesv/98bf8dbff0cc5eb0ba99802a1d3d460c) is the HTML code.

`/path/to/test/` is the full path to the folder `test` where `test.md` is located.

OK, so the problem is: pandoc & mermaid-filter can't create `img/diagram-2.png`.
However, if I run pandoc & mermaid-filter by command-line, the image is created, and then the preview works.

**Comment by lierdakil** [comment]
I imagine this is a bug related to https://github.com/Galadirith/markdown-preview-plus/pull/271. Could you check if it works with v2.4.5?

**Comment by pareyesv** [comment]
I updated to v2.4.5
and it works! Thanks!

However, there are still some problems: the image is not updated...

For example, If I write the following:

```mermaid

graph LR
    a-->b
    c-->d
```

the previewer works as expected, the image is displayed!

However, if I edit the image, for example, to:

```mermaid

graph LR
    a-->b
    c-->e
```

The previewer still displays the previous image. 

I guess the previewer is still displaying the image in cache?

**Comment by lierdakil** [comment]
From what I can tell from staring at the source code, images *should* be updated if those change on disk. I'm not sure why you're experiencing this problem here. It's possible you're running into some sort of a race condition. Does it *never* update, or does it always show the previous version?

**Comment by pareyesv** [comment]
It is related to #49. It comes from [markdown-preview](https://github.com/atom/markdown-preview/issues/207).

Step-by-step:

First, I restart atom.

Then I write first:

    ```mermaid
    
    graph LR
        a-->b
    ```

The previewer works as expected. The previewer displays the image.

Then when I change to:

    ```mermaid
    
    graph LR
        a-->c
    ```

The image is updated. So far so good.

When I change the image again:

    ```mermaid
    
    graph LR
        a-->d
    ```

the previewer doesn't update the image. Any new change won't be updated.

But, as I know that the image was written in `./img/diagram-2.png`, if I write:

    ```mermaid
    
    graph LR
        a-->d
    ```
    
    ![image](./img/diagram-2.png?v=123)

the first image doesn't update, but the second image is the right one (updated)
Notice that the number after `v=` can be any number.

Each time I change the number (different than the previous ones), the second image is updated (to the last/right version). 

The HTML source code is the following:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <meta name="generator" content="pandoc">
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
</head>
<body>
<p><img src="/path/to/test/img/diagram-2.png?v=1487772311976"></p>
<div class="figure">
<img src="/path/to/test/img/diagram-2.png?v=123" alt="image">
<p class="caption">image</p>
</div>
</body>
</html>
```

---
tested on:
- Ubuntu 16.04.1 LTS
- pandoc 1.19.2
- mermaid 7.0.0

**Comment by lierdakil** [comment]
Thank you for the detailed investigation. After staring at the code some more, particularly this line: https://github.com/Galadirith/markdown-preview-plus/blob/master/lib/image-watch-helper.coffee#L26 I might have a theory of what is actually going on. It might help to replace that line with 
```coffee
imageRegister[src].watcher.close()
delete imageRegister[src]
```
Can't tell if it'll help or not without being able to test properly, but it seems it's a good idea to change anyways, since otherwise some space and event leakage can occur if a file is routinely removed and recreated.

Sorry, but I'll leave that for tomorrow as well, since it's like 4 AM here. If you want to test if it helps for yourself, it's rather easy actually, just change the packages' source and restart Atom. And if you're wondering how on earth would you get to source code, there's a button in Atom's package properties (near bottom right corner in the picture):
![image](https://cloud.githubusercontent.com/assets/7275622/23239694/c8906d42-f979-11e6-9a6f-0a37ced06d3c.png)

**Comment by lierdakil** [comment]
Okay, so apparently I was right, and changing the source as I outlined fixes this. So released it as v2.4.6. If you could confirm that it works on your side, that would be great.

**Comment by pareyesv** [comment]
Sorry for my late reply...
Yes, it works!

There is an unwanted side effect: the _flashing/blinking_ image display
![mermaid_example](https://cloud.githubusercontent.com/assets/7954142/23335154/84f581b6-fbaf-11e6-88eb-456c4ed27881.gif)

The good news: This _blinking issue_ doesn't happen in previews without _mermaid code_.

**Comment by lierdakil** [comment]
Okay, I've reworked image update code to *not* trigger a complete re-rendering in v2.4.8. This should solve the flickering problem.

**Comment by lierdakil** [comment]
I'm assuming this can be closed. Let me know if I am mistaken.
