### ISSUE TITLE
Inline math equation starts with greek letter doesn't work

### ISSUE THREAD

**Issue by lizhaobin** [atom-community/markdown-preview-plus#286]
I would report my experience with inline equation starts by a greek letter. 

$\phi$  is not rendered but $2\phi$ is rendered.

**Comment by lierdakil** [comment]
Can't repro on my end. 
![image](https://cloud.githubusercontent.com/assets/7275622/25086006/c42986a8-236d-11e7-88d2-ec9bc6341183.png)
![image](https://cloud.githubusercontent.com/assets/7275622/25086011/ca4b2bd6-236d-11e7-84ee-669e460d6814.png)

**Comment by lierdakil** [comment]
ETIMEDOUT, closing.
