### ISSUE TITLE
Autocomplete citations from bib file

### ISSUE THREAD

**Issue by AustenLamacraft** [atom-community/markdown-preview-plus#287]
It would be great to have autocomplete for citations contained in a .bib file, as provided e.g. by the latexer or latextools packages for LaTeX.

**Comment by lierdakil** [comment]
There are packages to do exactly that, e. g. https://github.com/apcshields/autocomplete-bibtex. There is no point in reinventing the wheel, is there?

**Comment by AustenLamacraft** [comment]
Certainly not. Thanks for pointing it out.
