### ISSUE TITLE
Bullet causes table to display incorrectly

### ISSUE THREAD

**Issue by ttay24** [atom-community/markdown-preview-plus#288]
Bullet points prior to a table causes issues while parsing it. 

To reproduce:
1. Download attached markdown file: [error.txt](https://github.com/atom-community/markdown-preview-plus/files/950341/error.txt)
2. Drag and drop from Windows explorer to Chrome

Removing the bullet asterisk from line 4 resolves the issue.

**Comment by lierdakil** [comment]
From my tests, this happens with Pandoc parser only. This is Pandoc's "feature", I believe.

Generally speaking, there should be empty lines around bullet list for it to parse unambiguously.

**Comment by lierdakil** [comment]
ETIMEDOUT, closing.
