### ISSUE TITLE
LaTeX functionality

### ISSUE THREAD

**Issue by yochem** [atom-community/markdown-preview-plus#293]
In LaTeX you can do something like this:
``` tex
\begin{align}
E & = mc^2 \\
F & = ma \\
e^{i \pi} & = -1
\end{align}
```
with this as output: 
![output LaTeX](https://cloud.githubusercontent.com/assets/23235841/26122070/8aab7ccc-3a76-11e7-8dfb-fdbd29096337.png)
(the centering is on the '=')

Is it possible to use this with this package? If not, will it ever be?

**Comment by lierdakil** [comment]
Can't remember from the top of my head, but either

$$\begin{aligned}...

Or

$$\begin{align}

Should work.

вт, 16 Май 2017, 21:33 Yochem van Rosmalen <notifications@github.com>:

**Comment by yochem** [comment]
Awesome!! They both work 😄
