### ISSUE TITLE
Local file link with spaces in the file name is not rendering correctly

### ISSUE THREAD

**Issue by rszengin** [atom-community/markdown-preview-plus#295]
Writing in the markdown as: 
`[local copy](./Learning Options in Reinforcement Learning.pdf)`
is rendering **incorrectly** as:
`[local copy](./Learning Options in Reinforcement Learning.pdf)`

**but**

writing in the markdown as:
`[local copy](./LearningOptionsinReinforcementLearning.pdf)`
is rendering **correctly** as:
`local copy`

**Comment by lierdakil** [comment]
See http://spec.commonmark.org/0.27/#links

TL;DR spec forbids spaces in link target. Use %20 if you have to. We're
using markdown-it parser by default, which implements commonmark spec.

Alternatively, you might want to try pandoc parser, which is less strict,
but much less portable (i.e. Pandoc Markdown is very specific flavour)

пн, 29 Май 2017, 15:24 Rahman Salim Zengin <notifications@github.com>:

**Comment by lierdakil** [comment]
ETIMEDOUT, closing.
