### ISSUE TITLE
Diffrence between Github and Atom/Preview for Titles

### ISSUE THREAD

**Issue by Moejoe90** [atom-community/markdown-preview-plus#299]
I noticed in the Atom/Preview it is completely fine to do for example 
`##test` 
and get a Title test. However in Github actually parses as a string 
`##test`
and i would have to actually do 
`## test` 
for Github recognize that its a title. It would be cool to have that in the preview as well

**Comment by lierdakil** [comment]
Disable 'Use Lazy Headers' option in package settings and disable Pandoc parser if you're using it.

**Comment by lierdakil** [comment]
ETIMEDOUT, closing
