### ISSUE TITLE
Path to fallback bibfile

### ISSUE THREAD

**Issue by juancarloscastillo** [atom-community/markdown-preview-plus#300]
Firstly, congratulations and thanks for such a great package! I am new to Atom and I am attempting to generate a workflow for academic writing, so far very promising thank to tools such as this ones allowing links with bibfiles. I tried the option with the file within the same directory, works great, but I cannot manage to set the path to the "fallback bibfile", when the bib is an a different directorya, as in the image:
![image](https://user-images.githubusercontent.com/29175922/28310749-beb12874-6bad-11e7-9fc6-afff8a52077e.png)
I assume there is a wrong specification of the path, could you give me an example of how to do it? Thanks!

(I am on Ubuntu 14.04, Atom 1.18.0)

**Comment by lierdakil** [comment]
It doesn't work this way. This option was never intended for absolute paths. Algorithm stops at Atom project root. I would suggest symlinking your `/media/ntfs/Dropbox/MyLibrary.bib` to your project root (e.g. `ln -s /media/ntfs/Dropbox/MyLibrary.bib /home/user/articles/myNewArticle/`), and setting fallback bibfile to `MyLibrary.bib`, without path. Hope this helps.

**Comment by lierdakil** [comment]
ETIMEDOUT, closing
