### ISSUE TITLE
Duplicate pane launched when used

### ISSUE THREAD

**Issue by JavierReyes945** [atom-community/markdown-preview-plus#301]
# Duplicate pane launched when used

## Configuration
OS Ubuntu 16.04. I use Atom 1.18.0, and MPP 2.4.10. The package was installed correctly, and the Markdown-Preview core package is disabled, as stated in README.

## Followed procedure
When I launch the command `markdown-preview-plus:toggle`, it opens two panes (to the right).

## Screenshot
Duplicated pane
![bugmpp1](https://user-images.githubusercontent.com/17864163/28336123-15b9c7fe-6c01-11e7-8b6a-358e46bda6e4.png)

Preview core disabled
![bugmpp2](https://user-images.githubusercontent.com/17864163/28336124-15be0d96-6c01-11e7-943e-83c7554dd5e5.png)

**Comment by lierdakil** [comment]
Can't reproduce (on current beta). Maybe you just needed to restart Atom after disabling core markdown-preview?

**Comment by JavierReyes945** [comment]
As you might expect, I was about to give more info about the bug, and the problem was gone. I am pretty sure that I restarted Atom several times when it was failing. Apparently Murphy is playing with me. I am closing the issue.

**Comment by lierdakil** [comment]
Feel free to reopen if you run into this again. Bear in mind that I can't do much if I can't repro =\
