### ISSUE TITLE
Links don't work in preview

### ISSUE THREAD

**Issue by LenGrispani** [atom-community/markdown-preview-plus#303]
The links generated for references, citations, TOC, etc. do not work in the preview panel. The links are correctly displayed as links and are highlighted on mouse-over, but when you click on a link the position  of the text displayed in the preview panel is not re-located to the target position of the link. 

If you save as HTML and load into a browser, the links work fine. 

Thanks!

**Comment by lierdakil** [comment]
That's kind of expected, since we're basically pasting document inside Atom's DOM, so links would break. Not sure if we can do much about that tbh.

**Comment by LenGrispani** [comment]
I see. I view this as an essential feature when working with long documents using the pandoc-crossref and citeproc package.s If I want to navigate to a reference I see when reading the Atom preview, I have to  sync-source, find the MD reference, type the reference into the "find" window (can't cut and paste auto generated section references), then execute the find to jump to the required text position. Same thing for end-notes, citations, etc. but at least these reference can be cut-and-paste into the find box. Having this feature would let me use the preview as a very efficient source-file navigation tool. 

Adding these features seems a lot of work when the HTML export provides the navigation natively. Obviously, the HTML does not let you navigate back to the text within the MD, and the HTML output is not bad, but not as perfect as the lovely MPP output in Atom.  

Thanks for your reply!

**Comment by kiwi0fruit** [comment]
@lierdakil Can't we replace local cross-references with javascript "jumps" (may be GitHub uses something like that - cross-references do not work there when js is off. Same is for GitBook)?

We also can add js tooltips to external links (now it's even not clear where the link lead) with button to copy link.

**Comment by rriemann** [comment]
So the markdown-preview-enhanced package has functional links.

https://atom.io/packages/markdown-preview-enhanced

**Comment by kiwi0fruit** [comment]
@rriemann How are they implemented?

**Comment by lierdakil** [comment]
@rriemann I'm kinda tempted to say "well use that then" and be done with it. "But X has it" comment isn't all that helpful.

**Comment by rriemann** [comment]
Dear @shd101wyy, would you be so kind to point us to the part in https://github.com/shd101wyy/markdown-preview-enhanced that is responsible for making internal links (to footnotes and back) work? :)

**Comment by shd101wyy** [comment]
@rriemann 

`clickTagA`: https://github.com/shd101wyy/markdown-preview-enhanced/blob/0.15.2/src/preview-content-provider.ts#L339

`openFile`: https://github.com/shd101wyy/mume/blob/0.2.8/src/utility.ts#L133

Basically when you click a link, it will invoke `clickTagA` function. Then it will judge if it's a local file or http url, then open it correspondingly.

**Comment by kiwi0fruit** [comment]
@shd101wyy, thank you for response. Does it open local files for edit in Atom or somehow loads them to preview pane? Does it open external links in browser or in preview pane?

**Comment by shd101wyy** [comment]
@kiwi0fruit 

* If it's of type `'.pdf', '.xls', '.xlsx', '.doc', '.ppt', '.docx', '.pptx'`, then it will open it externally.
* If it's other type of local file, then it will open in Atom.
* Otherwise it will open externally.

**Comment by kiwi0fruit** [comment]
@shd101wyy if it was me to implement it I would replace external files logic with 'show in folder' (that select file). I wonder if it's possible...

**Comment by kiwi0fruit** [comment]
When using pandoc renderer this example doesn't work:

`test.md`:
```
# H1{#h1}

[H2](#h2).

# H2 {#h2}

[H1](#h1).
```

When clicking instead of moving to header Atom opens another empty pane named `test.md#h2`. When saving as PDF links work.
