### ISSUE TITLE
link display issue

### ISSUE THREAD

**Issue by wadecoding** [atom-community/markdown-preview-plus#304]
Hey, I have troubles using this plugin.

The problem is that links don't perform well on preview. They should be blue so that they can be recognized immediately, but they just show in white color, just as other plain contents do. But when move mouse onto them, they can be underlined and the cursor can be pointer.

So would you do me a favor and help me work this out?😁

**Comment by lierdakil** [comment]
Sanity check: did you remember to disable native `markdown-preview` package?

Hyperlink color depends primarily on your Atom theme, so if your theme defines foreground accents to be white, nothing we can do on our end.

You have several options though.

For one, you can enable 'Use GitHub.com Style' option in MPP settings, which will use github's default style for preview (white background, blue links, etc).

Alternatively, you can override hyperlink style in your Atom Stylesheet (Edit → Stylesheet...). For example, something like this might work:
```less
.markdown-preview a {
  color: blue !important;
}
```

**Comment by wadecoding** [comment]
- Sanity?
    - Check.
So yes, I of course disabled the native `markdown-preview` package. And I did before I start using this plugin. I read the README, dude...

My UI Theme is One Dark and Syntax Theme is Monokai. I thought they both are dark themes and didn't realize that themes can also affect hyperlink's preview.

Anyway, I change the stylesheet so now they are normal, THX.

**Comment by lierdakil** [comment]
> I read the README, dude...

Sorry if I offended you, that was not my intention.

After maintaining OSS projects for several years I learned to ask "sanity check" questions up-front. Experience tells me that even smartest people do sometimes make stupidest mistakes, so I find it's better to get that possibility out of the way first.

**Comment by wadecoding** [comment]
It's alright, I just wanna say that I watched the documentation before I ask for help. Never mind!

Best wishes.
