### ISSUE TITLE
Feature Request: Folding at heading tags

### ISSUE THREAD

**Issue by ianuzzi** [atom-community/markdown-preview-plus#307]
It would be really handy to be able to code-fold at the heading (#) tags.

**Comment by lierdakil** [comment]
Folding is usually handled by grammar. MPP doesn't have anything to do with that.

Official Atom's grammar for Markdown is here: https://github.com/atom/language-gfm
Community Markdown grammar is here: https://github.com/burodepeper/language-markdown

You might also want to take a look at https://github.com/JoseBlanca/markdown-folding, which promises the functionality you want (I don't know if it delivers though)

**Comment by ianuzzi** [comment]
Have you seen: (https://atom.io/packages/custom-folds)? Not sure if that would have the right parts of the Atom API referenced in it or not. I haven't written any Atom packages yet, so I don't really know. Hope the info is helpful. Thanks!
