### ISSUE TITLE
[feature request] footnote

### ISSUE THREAD

**Issue by franklinyu** [atom-community/markdown-preview-plus#308]
Example:

```markdown
Lorem ipsum dolor sit amet, nostrud facilisis an pro[^1].

[^1]: Vis dicant deserunt te, omnis vivendo sea cu.
```

Rendered as

> Lorem ipsum dolor sit amet, nostrud facilisis an pro<sup>[1](#user-content-ft-1)</sup>.
>
> <a id="ft-1"/>1. Vis dicant deserunt te, omnis vivendo sea cu.

See [Pandoc](https://pandoc.org/MANUAL.html#extension-footnotes) for specification.

**Comment by lierdakil** [comment]
Just use Pandoc parser/renderer. You know, this option:
![image](https://user-images.githubusercontent.com/7275622/30767681-99ff1d5e-a007-11e7-97d1-04daa81f6954.png)

**Comment by franklinyu** [comment]
How did I miss this…
