### ISSUE TITLE
Help with error This document format requires a nonempty title

### ISSUE THREAD

**Issue by cesarjorgemartinez** [atom-community/markdown-preview-plus#309]
Hi,

I have a md GFM file (without a title header: The GFM format not need required any title, and any metadata) that need to convert to html using pandoc.
Then I configured the plugin as:
- Use github.com style
- Pandoc options: Commandline arguments --to=html, --self-contained
- Pandoc Options: Markdown flavor: gfm

When I try to do Ctrl-Shift-M, i see:
Pandoc Error:
[warning] This document format requires a nonempty

HTML generated:
  <body class='markdown-preview'><h1>Pandoc Error:</h1><p><b>[warning] This document format requires a nonempty <title> element.
<br>! Please specify either 'title' or 'pagetitle' in the metadata.
<br>! Falling back to 'Untitled'
<br></title></b></p><hr></body>

But, If I use pandoc manually, works without problems, only show a warning, not an error, and generates the html correctly:
$ pandoc mydoc.md --self-contained -s -f gfm -t html -o mydoc.html
[warning] This document format requires a nonempty <title> element.
! Please specify either 'title' or 'pagetitle' in the metadata.
! Falling back to 'mydoc'
$ echo $?
0

Howto workaround this fail?

Regards

**Comment by lierdakil** [comment]
Okay, so `--standalone` argument to Pandoc isn't supported (technical reasons), and from quick look at Pandoc's code, I think you need to have that to get this warning. Also, it isn't present in any of the released Pandoc versions, so yeah.

Besides, this is first and foremost a *preview* package, exporting to html is just a small bonus -- you'll get *much* better results with using Pandoc directly anyway.

**Comment by cesarjorgemartinez** [comment]
Hi,
I'm using last nightly build of pandoc, because multiple errors of official versions.
https://github.com/pandoc-extras/pandoc-nightly/releases/tag/hash-fc25e3a5

I did tests, and:
--standalone is supported
-s (short) no
If I include --quiet, then the warning not appear and the conversion is correct.

I like using this for conversion because is more comfortable and faster.

**Comment by cesarjorgemartinez** [comment]
And the base64 conversion and accents?

**Comment by maheshKulkarniX** [comment]
> **Simple way to resolve this issue Just Add**
`README.md` in **.Rbuildignore File**
