### ISSUE TITLE
Using pandoc problems relative urls and distinct formats

### ISSUE THREAD

**Issue by cesarjorgemartinez** [atom-community/markdown-preview-plus#310]
Hi,

I am using this plugin to convert md files (GFM format) to html files (self contained images). Use last pandoc: https://github.com/pandoc-extras/pandoc-nightly/releases/tag/hash-fc25e3a5

I use pandoc configuration in the plugin:
- Use github.com style
- Pandoc options: Commandline arguments --quiet, --from=gfm, --to=html, --standalone, --self-contained
- Pandoc Options: Markdown flavor: gfm

When I save the file:
- URLs not managed correctly, and don't see anymore. I have a link as: `<img src="./logo.jpg">`
  When I see the html self contained:
`<img src="C:\AbsolutePath\data:image\jpeg;base64,\9j\7AARRHVja3kAAQAEAAAAUAAA\+4ADkFkb2JlAGTAAAAAAf\bA...`
  Using manually pandoc (pandoc mydoc.md --self-contained -s -f gfm -t html -o mydoc.html):
`<img src="data:image/jpeg;base64,/9j/7AARRHVja3kAAQAEAAAAUAAA/+4ADkFkb2JlAGTAAAAAAf/bA...`
  See differences:
  - Create absolute paths (If we use relative paths, not need to change to absolute path, and also, if we use --self-contained, then need always to remove absolute paths.
  - Creates base64 changing `\` to `/`.
- Other thing, create the html with multiple differences:
  - Insert multiple lines of no GFM format (a example .markdown-preview lines.
  - The accented characters is changed to Ascii codes, when not need:
    - In pandoc execution example:

    ```
    <ul>
    <li><a href="#1-title-with-í-char">1. Title with í char</a></li>
    ```

    - Using the html generated with this plugin:

    ```
    <ul>
    <li><a href="#1-title-with-&#xED;-char">1. Title with &#xED; char</a></li>
    ```

I think that exists other differences, you can to create these html files and use a Kdiff tool to see.

If I use pandoc in this plugin, only need to launch the pandoc program, with the options, not do other things?

Regards

**Comment by lierdakil** [comment]
v2.4.12 should handle data URIs correctly. Sorry it took so long to fix that.

`--standalone` option is still not supported, and likely won't be for the foreseeable future -- it might work, at first glance, but equally probable that it will break randomly. Use at your own risk.

**Comment by lierdakil** [comment]
oh, right, hrefs should be urlencoded instead of htmlentity-encoded, I forgot about that.

**Comment by lierdakil** [comment]
Okay, done in v2.4.13. Note that those *should* be urlencoded -- Pandoc deviates from spec in this regard.
