### ISSUE TITLE
Compile the preview even if undefined references arise

### ISSUE THREAD

**Issue by stakaz** [atom-community/markdown-preview-plus#312]
It would be great when the preview would still be available if some references are undefined (pandoc-crossref).

This would make it possible to work on project with multiple files. Unlike double defined references the missing reference is just a warning and not an error. 

Read this thread for a detailed problem explanation: https://github.com/lierdakil/pandoc-crossref/issues/136#issuecomment-337618023

**Comment by lierdakil** [comment]
Just released v2.4.11 which should handle Pandoc errors in a saner (i.e. more useful) way. Please let me know if something breaks unexpectedly.

Also sorry it took so long. Apparently to make it work I had to rewrite about half of Pandoc-related logic.
