### ISSUE TITLE
stdout maxBuffer exceeded error on long documents

### ISSUE THREAD

**Issue by scarwire** [atom-community/markdown-preview-plus#316]
Hi there everyone,

I'm working with a quite long markdown document, and whenever it goes over a certain length I get a "stdout maxBuffer exceeded" error.

For a minimal working example, paste exactly 204090 characters of lorem ipsum or whatever gibberish you want and do a markdown preview: no problem. Then add one more character and you'll get the error message, and any further characters will not be previewed.

This bug is definitely not coming from pandoc, since I can take the same file and process it directly through pandoc on the command line without the error.

Anyone else encounter this bug or know a workaround?

All best,
Daniel

**Comment by lierdakil** [comment]
Sorry, that's probably my fault. See if 2.4.16 fixes this problem.

**Comment by scarwire** [comment]
Brilliant! Thanks for the quick fix!

**Comment by lierdakil** [comment]
Glad to know my fix worked. Thanks for reporting!
