### ISSUE TITLE
How enable this theme?

### ISSUE THREAD

**Issue by caiotarifa** [atom-community/markdown-preview-plus#317]
When I downloaded the package I liked the light theme of the screenshot, but I can't find how to activate it.

Is it possible to use it?

![Theme](https://raw.githubusercontent.com/atom-community/markdown-preview-plus/master/imgs/mpp-full-res-invert.png)

**Comment by lierdakil** [comment]
"Use GitHub.com style" in package settings.

**Comment by caiotarifa** [comment]
Thank you, but it isn't similar to GitHub.com style.

**Comment by lierdakil** [comment]
Well, it is, at least wrt Markdown rendering. White background, black text, blue hyperlinks. It's actually something we've inherited from [Atom's markdown-preview](https://github.com/atom/markdown-preview/blob/master/styles/markdown-preview-github.less)
