### ISSUE TITLE
Using Atom's Docks

### ISSUE THREAD

**Issue by lierdakil** [atom-community/markdown-preview-plus#318]
@niccolomineo:
> Not sure whether it's already mentioned somewhere else, but moving to Atom's collapsible pane containers,"Docks", could also be worth adding to the list.

I'm not sure using docks makes much sense in this particular case. Abstractly, there's not much difference between docks and what we're using right now -- it's entirely possible to manually move preview pane into a dock, actually:
![image](https://user-images.githubusercontent.com/7275622/32172514-f2ed7602-bd8c-11e7-8846-6bd1abf44fe7.png)

Whether it makes sense to use docks by default though, that's debatable. I, for one, don't think that dock is supposed to be particularly wide/tall, and if it's not, displaying a preview in it... wouldn't look that good, let's put it that way
![image](https://user-images.githubusercontent.com/7275622/32172675-7c901d60-bd8d-11e7-9736-65303ed572f5.png)

**Comment by 50Wliu** [comment]
> I'm not sure using docks makes much sense in this particular case.

I agree.  I think a regular pane item makes a lot of sense for Markdown Preview.  Then you can move it into a dock if you so choose.

**Comment by niccolomineo** [comment]
Its dockeability is useful especially for atom-ide-ui users. I think it would be fair to at least leave the choice to the user via settings panel.

**Comment by 50Wliu** [comment]
> I think it would be fair to at least leave the choice to the user via settings panel.

As @lierdakil mentioned, that is already possible:

> it's entirely possible to manually move preview pane into a dock, actually

**Comment by niccolomineo** [comment]
Will it stay docked for good? Or is it going to show up again as a panel when I restart Atom?

**Comment by lierdakil** [comment]
> Will it stay docked for good? Or is it going to show up again as a panel when I restart Atom?

When you restart Atom, yes, or at least it should. Also, it's not a panel, panels aren't draggable.

*New* previews will still open in a pane though, so that might be a bit of an annoyance.
