### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by lengyuwuxin** [atom-community/markdown-preview-plus#320]
logs：
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | linux | x64
gyp http GET https://atom.io/download/electron/v1.6.15/iojs-v1.6.15.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 54.231.80.232:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Linux 4.9.0-deepin9-amd64
gyp ERR! command "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.6.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /home/keagan/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

I had install nodejs 9.2 in my conputer .I can't install  that.
I think it  may have something to do with my nodejs 9.2 , but I can't solve  that

**Comment by lierdakil** [comment]
Looks like Internet connectivity problem: `Error: connect ETIMEDOUT 54.231.80.232:443`
