### ISSUE TITLE
Reusing MPP in Jupyter Markdown package

### ISSUE THREAD

**Issue by kiwi0fruit** [atom-community/markdown-preview-plus#322]
[github.com/kiwi0fruit/markdown-preview-plus](https://github.com/kiwi0fruit/markdown-preview-plus) is not a pull request actually. It's the demonstaration of:
* moving font settings to the MPP GUI
* tweaking css styles for better look.

And it's not the final result (it's far from it).

About a fork. Actually I'm making a RMarkdown alternative on python+jupyter basis. It would have atom GUI package. So there would be a separate atom package written in javascript (not coffeescript). It would work with pandoc only. It would have pandoc options manager that can switch pandoc options from a predefined profiles.

And I'm going to reuse MPP in this GUI. The way it would be done is still to be considered.

**Comment by kiwi0fruit** [comment]
@lierdakil And about `atom-highlight`. I simply needed a working prototype with patches made to `atom-highlight`. I needed to fix font fallback in source code blocks. When using space -> nbsp replacement font fallback with combining characters leads to the whole line switching to the fallback font. For more detail see: https://github.com/atom-haskell/atom-highlights/pull/1

**Comment by lierdakil** [comment]
Okay, thanks for sharing. I never said no to making configuration more accessible, so I hope you PR that at some point. Can't say anything about CSS tweaks though, since I'm primarily using dark theme and pseudo-GitHub style.

**Comment by kiwi0fruit** [comment]
I guess MPP would be reused in Pandoc profile manager package via suggesting PR with [service API](http://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/) specifically for profile package.

**Comment by kiwi0fruit** [comment]
Closing until this issue really needed.

**Comment by kiwi0fruit** [comment]
Is it possible to call MPP on Markdown file (maybe opened in Atom) from another Atom package (like unix-filters)? So that preview pane appear. And even export to html/pdf right after that (from another package).

**Comment by lierdakil** [comment]
You can run commands via `atom.commands.dispatch`. Make sure you're running those on correct elements though. Take a look at https://github.com/atom-community/markdown-preview-plus/blob/master/menus/markdown-preview.cson to get an idea of what commands are available and on which elements those are intended to be dispatched.

See also: https://github.com/atom-community/markdown-preview-plus/issues/376

**Comment by kiwi0fruit** [comment]
Thank you!

чт, 31 мая 2018, 10:32 Nikolay Yakimov <notifications@github.com>:

**Comment by kiwi0fruit** [comment]
@lierdakil

I'm looking for any advice available. Is there a way implement calling MPP from outside of Atom? I develop [pandoctools](https://github.com/kiwi0fruit/pandoctools) - profile manager of text processing pipelines: Pandoc filters, any text CLI filters.

Pipelines are defined in a bash script. And find it to a be the best language for defining text processing pipelines.

I also like the MPP export to HTML that uses code styles from Atom and it's consistent to export to the same thing as to you saw on preview.

I know that this can done on Atom side but I feel like adding API to access Atom is better from UX of the user that defines text pipiles.

This needs creating some kind of API to access MPP from other applications. Do you have any advice? The only thing I can now think about is to create an Atom package that starts web server and communicate with MPP via Atom commands API. And the outer apps communicate with that web server.

Maybe there is a better way? Not a web server but another API?

**Comment by lierdakil** [comment]
Atom doesn't really have any built-in remote control capabilities as far as I am aware, so you'll have to roll your own anyway. That is unless you're content with running Atom headless to just run export-to-*, in which case, it'd be unclear why do you need Atom at all, Pandoc is perfectly capable of doing that by itself.

So... yeah, the "web server" idea doesn't seem like you thought that through completely, but you're thinking along the right lines I reckon. I would probably try to build something over OS sockets with [node-ipc](https://www.npmjs.com/package/node-ipc), but other options are available, say [json-rpc over TCP](https://www.npmjs.com/package/jayson)

**Comment by kiwi0fruit** [comment]
Thanks!

Actually I need this with running Atom. As the main target is Hydrogen. See [this issue](https://github.com/nteract/hydrogen/issues/1342). I already have pandoc filter that runs Jupyter and collects outputs. But it starts new Jupyter every time and I already use Hydrogen for writing documents with code insertions - why not unify. But I really want to have a single bash script... So this strange idea appeared.

If having Hydrogen - then it would be easy to have MPP as well.

**Comment by kiwi0fruit** [comment]
I guess I'll first deside where I want an executable to be placed - it seems that it should be in python environment with pandoctools. So then I need a communication protocol that is easily available from both Node.js and Python.

**Comment by lierdakil** [comment]
Python has libraries for json-rpc.

**Comment by kiwi0fruit** [comment]
Seems like a good option. I guess Jupyter output is JSON already.

**Comment by kiwi0fruit** [comment]
### Markdown+HTML as PDF, MS Word and others killer

@lierdakil See the [**dream description**](https://github.com/kiwi0fruit/misc/blob/master/pdf_and_word_killer.md).
