### ISSUE TITLE
support for pweave (.pmd)

### ISSUE THREAD

**Issue by HenrikEckermann** [atom-community/markdown-preview-plus#324]
Hi there,

I noticed that there is support for .rmd files (at least for many features: I only noticed that inline code e.g. gets not executed and printed but I guess that requires knitr functionality).

But for .pmd files [(Pweave)](http://mpastell.com/pweave/) which uses pandoc markdown, there is no support.

It would be great if you could add that.  I think this is practically pandoc markdown support.

Best regards,
Henrik

**Comment by lierdakil** [comment]
We have direct support for Pandoc, if you need it, check package settings. You'll have to install Pandoc though. By default the package uses markdown-it, which follows [commonmark spec](commonmark.org) more or less (there are some extensions we added, like math and lazy headers, but that's about it). 

Reimplementing Pandoc (at least Markdown -> HTML bits) would seem to be rather pointless, and what's more important, is a **lot** of work. We don't have the manpower for that.

**Comment by lierdakil** [comment]
ETIMEDOUT, closing.
