### ISSUE TITLE
kramdown $$

### ISSUE THREAD

**Issue by mlund** [atom-community/markdown-preview-plus#327]
I'm using kramdown syntax for my markdown files where math blocks and inline math are both defined by double dollar signs, $$ ... $$. Blocks preview fine, but inline math will not render as math. Is there a way to remedy this?

**Comment by mlund** [comment]
In the markdown-preview-enhanced package, custom delimiters can be used to display Kramdown math by setting

1. inline to `["$$", "$$"]` and
2. blocks to `["$$\n", "\n$$"]`

(require a newline immediately before and after math for blocks). Perhaps something similar could be implented here?

**Comment by lierdakil** [comment]
Making delimiters configurable is somewhat trivial. Coercing those to respect newlines is not.

A quick question, how would that handle something like this:

```markdown
1.  This is a simple Markdown list
2.  And here we put some display math, that should be *inside* the list

    $$
    \int_0^\infty \exp(-x) \mathrm{d} x
    $$
```

Some initial work in https://github.com/atom-community/markdown-preview-plus/pull/337, but I'm not entirely sure it will handle all the edge cases. Certainly won't handle *several* newlines in math delimiters, i.e. only `\n...`, `...\n` and possibly `\n...\n` are meaningful, and *only* in block math. Basically, it's a hack.
