### ISSUE TITLE
link markdown breaks if URL contains ')' [bug]

### ISSUE THREAD

**Issue by AddaxSoft** [atom-community/markdown-preview-plus#329]
reproduce:
`this is a [link](http://somewhereintheinternetnet.com//linkto-(file)-here.pdf)
`
this breaks the markdown rendering in the plugin and will display broken link like this:
`this is a link-here.pdf)`

![image](https://user-images.githubusercontent.com/6898938/34628105-76cef5bc-f263-11e7-8f6a-5a5440b14e4a.png)

correct behavior:
this is a [link](http://somewhereintheinternetnet.com//linkto-(file)-here.pdf)

**Comment by lierdakil** [comment]
First of all, can't reproduce.

Second, CommonMark spec requires links with special characters be enclosed in `<>`, e.g. `[link](<http://somewhereintheinternetnet.com//linkto-(file)-here.pdf>)`. See latest CommonMark spec [here](http://spec.commonmark.org/0.28/)

Third, this project doesn't handle Markdown parsing. Depending on your chosen parser, it's either markdown-it (the default), or Pandoc. If you think this is a bug, raise an issue on the relevant repo. Although both follow CommonMark spec to some degree, so the resolution would most likely be "use `<>`".

**Comment by AddaxSoft** [comment]
Thanks for your reply; how do I know which parser I'm using?

even after including `<>` I still get this:
![image](https://user-images.githubusercontent.com/6898938/34639798-189e14ee-f2e7-11e7-8236-b825cbaa97aa.png)

**Comment by lierdakil** [comment]
Actually it would seem you're either using Atom's [bundled markdown-preview](https://github.com/atom/markdown-preview) and confusing that with markdown-preview-**plus**, or you just forgot to disable bundled markdown-preview.

Provided it's the latter, try doing something like this:
![image](https://user-images.githubusercontent.com/7275622/34639852-ee21064c-f2f8-11e7-8e1e-4dd7c4627eab.png)
