### ISSUE TITLE
pandoc

### ISSUE THREAD

**Issue by stupidYellowBird** [atom-community/markdown-preview-plus#333]
Error: Command failed: D:\Pandoc\pandoc.exe --from=markdown-raw_tex+tex_math_single_backslash --to=html --filter=pandoc-citeproc -f markdown -o slide.html -s -t revealjs Unknown writer: revealjs

**Comment by lierdakil** [comment]
> Unknown writer: revealjs

Well, that's kinda obvious, isn't it? Check your Pandoc version. Check for runaway spaces in settings, it might be `revealjs ` or ` revealjs`. Not a bug.

**Comment by lierdakil** [comment]
As I said, check for runaway spaces.

**Comment by lierdakil** [comment]
I should mention though that any output format besides HTML won't work as you expect, since it should be directly embeddable into Atom's DOM

**Comment by stupidYellowBird** [comment]
I don't quite understand your mind.
Is there any problem in my settings file  _config.scdn_ ?
```
"*":
  "autocomplete-python":
    useKite: false
  core:
    disabledPackages: [
      "linter-markdown"
      "autocomplete-python"
      "autoclose-html"
      "seti-icons"
      "latex"
      "markdown-preview"
      "markdown-preview-enhanced"
      "language-gfm"
    ]
    telemetryConsent: "limited"
    themes: [
      "one-dark-ui"
      "base16-tomorrow-light-theme"
    ]
    uriHandlerRegistration: "always"
  editor:
    fontSize: 20
    softWrap: true
    tabLength: 4
  "exception-reporting":
    userId: "feb19e26-3e79-46db-bf1a-0190eb980692"
  "markdown-preview":
    breakOnSingleNewline: true
    useGitHubStyle: true
  "markdown-preview-enhanced": {}
  "markdown-preview-plus":
    breakOnSingleNewline: true
    enablePandoc: true
    pandocArguments: [
      "-t <space>revealjs<space>"
      "-s"
    ]
    pandocBibliography: true
    pandocPath: "C:\\Users\\Administrator\\AppData\\Local\\Pandoc\\pandoc.exe"
    useNativePandocCodeStyles: true
  "markdown-themeable-pdf": {}
  "markdown-writer": {}
  pandoc: {}
  welcome:
    showOnStartup: false
".md.text":
  editor:
    softWrap: true
    softWrapAtPreferredLineLength: false
```

**Comment by stupidYellowBird** [comment]
`--to=revealjs ,-s` instead of `-t revealjs ,-s`,Atom doesn't pop up error reporting

**Comment by lierdakil** [comment]
That's what I was talking about. Runaway spaces. It either has to be `-trevealjs` or `-t,revealjs`. Otherwise Pandoc will parse space as part of format name and get confused. 

Fyi, Pandoc's standalone output is not supported by this package, so you're on your own. It's about as likely to break as it is to work.
