### ISSUE TITLE
Saving as HTML doesn't save output file

### ISSUE THREAD

**Issue by michalbielejewski** [atom-community/markdown-preview-plus#334]
**Prerequisites**
* [x] Can you reproduce the problem in safe mode?
* [x] Are you running the latest version of Atom?
* [x] Did you check the debugging guide?

**Atom:** 1.24.0-beta3 x64
**OS**: Windows 10 

**Steps to Reproduce**
1. Open a Markdown file, or create new
2. Ctrl + Shift + M
3. Context Menu -> Save as HTML...
4. Select file
5. Click Save

**Expected behavior**: HTML file get saved and opened in new pane in Atom
**Actual behavior**: Files is not saved nor opened, nothing is happening actually

I've tried:
* Checking the DevTools console
* Deleting `.atom` folder
* Disabling all not built-in packages
* Running Atom in safe mode

**Versions**
```
Atom    : 1.24.0-beta3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
![bug](https://user-images.githubusercontent.com/11682584/34907376-e025c94e-f87d-11e7-90b1-8394bb6fbdce.gif)

**Comment by lierdakil** [comment]
> Disabling all not built-in packages

Uhhh... Are you sure you're not confusing this package with built-in [markdown-preview](https://github.com/atom/markdown-preview) then? Since markdown-preview-**plus** is most certainly *not* built-in.

**Comment by lierdakil** [comment]
You most certainly do. Closing as invalid.
