### ISSUE TITLE
Keybindings for bolding, italicizing, etc... 

### ISSUE THREAD

**Issue by JohnGiorgi** [atom-community/markdown-preview-plus#346]
It seems that keybindings for bolding and italicizing a word (i.e., just like you might select a word and use `cmd + B` to bold a word in a WYSIWYG editor) would be immensely useful. 

As far as I can tell this does not exist (please let me know if I am mistaken). I'm not even sure where I would start to implement this function, so if someone more talented than me wants to give it a shot I would be thankful!

**Comment by lierdakil** [comment]
Check markdown-writer package. We're only concerned with preview, so various editing niceties are out of scope.
