### ISSUE TITLE
Using convert to PDF feature

### ISSUE THREAD

**Issue by JakartaLaw** [atom-community/markdown-preview-plus#347]
Love the package!

However, im unsure whether or not it's possible convert the markdown file to PDF:

From:
https://github.com/travs/markdown-pdf/pull/88

I read, that it should be possible?

Best Regards

**Comment by lierdakil** [comment]
Did you try installing and using markdown-pdf package? Apparently, a bug that prevented it from working with MPP was fixed at some point, but I'm not 100% sure it *actually* works (probably should've added some tests related to that)

**Comment by lierdakil** [comment]
Ah, no, disregard that. markdown-pdf went into a completely another direction at some point and it doesn't really work with the current release of MPP (and it didn't work properly or at all in like forever). I will push out a release that should *kinda* work if you enable "fallback mode" in markdown-pdf, but yeah, that's not really supported.
