### ISSUE TITLE
SaveAs HTML Not Work in preview pane.

### ISSUE THREAD

**Issue by WuZhuoran** [atom-community/markdown-preview-plus#350]
OS: Windwos 10 / Mac OS
Atom: Latest
MPP: Latest

After writing a markdown file, I go to preview pane. Then I want to save as HTML as a new file.

But nothing happened.

No error message. No new file created.

How to fix this.

**Comment by lierdakil** [comment]
Thanks for reporting.

It's an Atom bug https://github.com/atom/atom/issues/16801

Specifically, in 1.24.0.

I just pushed out MPP v2.5.3, which includes a workaround.

**Comment by WuZhuoran** [comment]
Thanks @lierdakil 
It works now.
