### ISSUE TITLE
NewUser different print sizes get me confused

### ISSUE THREAD

**Issue by xxml** [atom-community/markdown-preview-plus#353]
After a recent update, I tried to convert my .md file to HTML and print.(i use a plugin package called markdown preview plus).

 But the font or the size of the page became larger than before. I have not change any theme nor font size. It seems like the page have been zoomed in.

This is current preview of the pages.
![111](https://user-images.githubusercontent.com/36726872/36527661-6cf7d990-1767-11e8-9f48-9ce547113387.png)

This is what I had printed before.
As you can see current page is only half of the context as before.
![222](https://user-images.githubusercontent.com/36726872/36527701-94733ce4-1767-11e8-9ec4-5d51b6842daf.jpg)

Any one have similar issue or know how to solve this ?

**Comment by lierdakil** [comment]
Thanks for reporting. This seems like a weird bug in WebKit's rendering engine since not much has actually changed. Anyway, v2.5.4 reverts to old layout of exported HTML files, so it should work as you would expect. Sorry for the trouble.
