### ISSUE TITLE
How to change the Chinese font of the generated PDF file？

### ISSUE THREAD

**Issue by JamesZBL** [atom-community/markdown-preview-plus#359]
I have changed the github-markdown.css in the .atom folder, but modifying the "font-family" does not work. Does it not support fonts installed locally on the system?
![default](https://user-images.githubusercontent.com/26003056/37503852-d62608dc-2915-11e8-9a6c-58f2146139cc.png)

**Comment by lierdakil** [comment]
...No idea. If you're using markdown-pdf, consider asking them https://github.com/travs/markdown-pdf.

**Comment by lierdakil** [comment]
ETIMEDOUT
