### ISSUE TITLE
Code-blocks are not scrollable in the generated HTML

### ISSUE THREAD

**Issue by anddero** [atom-community/markdown-preview-plus#360]
By saving the markdown preview as HTML with `Save As HTML...`, the code-blocks which have the following form in markdown:

    ```
    // code here
    ```

are not scrollable in the HTML.
If lines are too long, the output is displayed as such:
![image](https://user-images.githubusercontent.com/9193126/37596352-921eb244-2b84-11e8-82e5-3f9050d622df.png)

The whole page can be scrolled instead:
![image](https://user-images.githubusercontent.com/9193126/37596407-bdba90d0-2b84-11e8-814a-73b75bb17268.png)

Expected design would be (as in the preview pane), scrollable:
![image](https://user-images.githubusercontent.com/9193126/37596529-1f4050d8-2b85-11e8-92e0-b6c388b1564c.png)

**Comment by lierdakil** [comment]
Thanks for reporting. Should be fixed in v2.5.6.
