### ISSUE TITLE
Preview is not working here is a picture of what happens when I press ctrl+shft+m

### ISSUE THREAD

**Issue by JonDevOps** [atom-community/markdown-preview-plus#361]
![send to atom markdown previe plus](https://user-images.githubusercontent.com/30133774/37625700-5dc441b6-2ba3-11e8-8aca-34697b1a7424.PNG)

As you can see(to the right) that is now what live preview is suppose to do. It just makes boxes of code...

Please fix. If this isn't an issue PLEASE tell me what I'm doing wrong. I would be depressed if I have to got to another live previewer. I liked this one because it loads in milliseconds compared to 47 seconds like the last one I had, and it is being developed by the atom community. Please and thank you.

**Comment by lierdakil** [comment]
Uh... How do you figure a *Markdown* previewer is supposed to work with plain HTML? Just use an HTML preview package... (for instance, https://atom.io/packages/atom-html-preview)

**Comment by lierdakil** [comment]
ETIMEDOUT
