### ISSUE TITLE
Preview throws warning with pandoc 2.1.1

### ISSUE THREAD

**Issue by gunwald** [atom-community/markdown-preview-plus#362]
This great extension does not work well with latest Pandoc version:

```
pandoc --version
pandoc 2.1.1
Compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.6
```

The preview is rendered but throws the following message at the top:

```
Pandoc Error:
[WARNING] Deprecated: --latexmathml, --asciimathml, -m
```

**Comment by lierdakil** [comment]
We don't set those options. Those are probably set in your config. So... update your config?

**Comment by lierdakil** [comment]
ETIMEDOUT
