### ISSUE TITLE
Odd problem with header rendering

### ISSUE THREAD

**Issue by nightrune** [atom-community/markdown-preview-plus#367]
I had a document with the markdown 

```
### Theme
```

and it looked like it broke css rendering. It was all flat text but bold and items still worked. Rendering works if I just change the tag to 

```
### Themer
```

or 

```
### Themes
````

**Comment by lierdakil** [comment]
A minimal test case would be nice since it's not apparent how this can be reproduced from the report.

**Comment by nightrune** [comment]
I'll build one and post then.

**Comment by nightrune** [comment]
Tested in Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Negative Case
`
# This markup doesn't work

### Theme
There is the theme

#### The content after this is just to show that it doesn't render correctly
* No win conditions for this one

#### Header!
* Point 1
* Point 2
* Point 3

```
Code Here
```
`
Positive Case
`
# This markup does work

### Themer
There is the theme

#### The content after this is just to show that it doesn't render correctly
* No win conditions for this one

#### Header!
* Point 1
* Point 2
* Point 3

```
Code Here
```
`

**Comment by lierdakil** [comment]
Ah... Sorry, are you perhaps trying to report a bug in [this Chrome plug-in](https://chrome.google.com/webstore/detail/markdown-preview-plus/febilkbfcbhebfnokafefeacimjdckgl)? I believe that one lives at https://github.com/volca/markdown-preview. This repo is for a similarly-named [Atom editor plug-in](https://atom.io/packages/markdown-preview-plus).

**Comment by nightrune** [comment]
Oh, sure is. Sorry about that, please close!
