### ISSUE TITLE
Generate html: Add one option to open url in new window

### ISSUE THREAD

**Issue by jefferyyuan** [atom-community/markdown-preview-plus#368]
We often generate html from markdown text and publish to our blogs.

It would be great to add one option, so when we generate html from markdown text, we can choose to open url in new window - add target="_blank" in the link.

Thanks

**Comment by lierdakil** [comment]
Okay, so I don't really understand the request here. Just in case, you sure you didn't mean to report this to https://github.com/volca/markdown-preview instead?

**Comment by lierdakil** [comment]
ETIMEDOUT
