### ISSUE TITLE
Removing myself as a maintainer

### ISSUE THREAD

**Issue by leipert** [atom-community/markdown-preview-plus#370]
@atom-community/markdown-preview-plus @atom-community/owners 
Sorry for the long-time silence, but I finally took the courage to do what's right and am going to remove myself as a maintainer from this repository. I am neither using MPP nor atom anymore, it was a fun time developing together with you @Galadirith, and it seems like @lierdakil took up the efforts really well. I wish you all the best!

**Comment by lierdakil** [comment]
Not sure what to say beyond "best wishes to you too". Not sure if I agree with you that removing yourself is "right", but I won't argue about that. So... yeah, best wishes to you too.
