### ISSUE TITLE
How to change the background's color of the preview style ?

### ISSUE THREAD

**Issue by clock-z** [atom-community/markdown-preview-plus#372]
your background of preview style is white.
<img width="884" alt="2018-04-26 9 28 09" src="https://user-images.githubusercontent.com/37953042/39308847-18c516da-4999-11e8-9b2a-b81ab0a4c2a1.png">

my background of preview style is black.
<img width="1019" alt="2018-04-26 9 31 12" src="https://user-images.githubusercontent.com/37953042/39308888-33c4db8c-4999-11e8-96cd-d50b030b4f34.png">  

This is the first time that I have used the atom in MAC and closed the atom's package of `markdown-preview`.  

 **I want to change my background of preview style as yours.**

my style.less:
```
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// style UI elements inside atom-text-editor
atom-text-editor .cursor {
  // border-color: red;
}
```

Use @lierdakil's method:
 ```markdown-preview-plus-view``` element selector instead, f. ex.:
```
markdown-preview-plus-view {
  background-color: red !important;
}
```
However my font color is white though that i can't recognize them.
<img width="1021" alt="2018-04-26 9 34 35" src="https://user-images.githubusercontent.com/37953042/39309041-a87503c6-4999-11e8-87f1-478c89ae3c51.png">

**Comment by lierdakil** [comment]
Enable `Use GitHub.com style` option in package settings.

**Comment by clock-z** [comment]
Thank you!
