### ISSUE TITLE
blockMathSeparators option seems to be ignored

### ISSUE THREAD

**Issue by alcrene** [atom-community/markdown-preview-plus#381]
I've stumbled across the following trying to configure markdown-preview-plus for my needs: If I have the following in my `.atom/config.cson` (this is just for testing):

```
  "markdown-preview-plus":
    blockMathSeparators: [
      "\\["
      "\\]"
      "||"
      "||"
    ]
```
then I would expect
```
$$x^2$$
```
to not be rendered in the live preview, but
```
|| x^2 ||
```
to be. In fact the opposite happens, suggesting that the `blockMathSeparators` option is not read at all, and that a hardcoded value is used in all cases.

The reason  I want to modify `blockMathSeparators` is that wrapping all my display math in `$$` or `\[` is not a workable solution for writing a longer form document, as pandoc's export to latex then does not compile. Ideally naked environments like `\begin{equation}` -- `\end{equation}`

I'm using the current release, markdown-preview-plus v.3.0.1.

**Comment by lierdakil** [comment]
blockMathSeparators only works with markdown-it parser/renderer. Pandoc does not allow configuring math delimiters (also `\[` doesn't work in Pandoc, only `$` for inline and `$$` for display math are allowed)

**Comment by alcrene** [comment]
Ah, I see. Pandoc does however recognize naked math environments – is this something you plan to support at some point ?

**Comment by lierdakil** [comment]
Pandoc doesn't actually "recognize" naked math environments. What it does is passes those through to LaTeX. For any other output formats, those will be mercilessly discarded.

If you want to label/reference your equations in Pandoc, you might be interested in https://github.com/lierdakil/pandoc-crossref

**Comment by alcrene** [comment]
Right, I had missed that. Thanks for the tip !
