### ISSUE TITLE
Various problems with bullet lists.

### ISSUE THREAD

**Issue by jplflyer** [atom-community/markdown-preview-plus#386]
If you put the below into a .md file, the comments will explain the issues. Basically there are issues with blank lines. Some of them are "fixed" and some only occur when you type, but if you close the preview and open it again, it displays properly at least for a while.

--- Cut here ---

This shows issues with nested bullet lists.

This looks fine.

* One
* Two
* Three

This puts blank lines after the bullets but before their text, which makes no sense at all. But
it's weirder than that. If might appear correctly when you first open this
document, but then if you delete the blank lines between the bullets and
then put the blanks back in, that's when the behavior turns weird.

* One

* Two

* Three

For some reason, this doesn't have the same exact problem. Instead,
it puts a blank line after the top level bullets and before their
nested list, but NOT before the next top level bullet. That is,
One (blank line), One-A, One-B, (no blank line), Two (blank line) etc.
This is basically the opposite of what is desired. This behavior appears
fixed and is unrelated to whether you've been editing (although it might
duplicate the above behavior during editing).

* One
  - One-A
  - One-B

* Two
  - Two-A
  - Two-B

* Three
  - Three-A
  - Three-B

**Comment by lierdakil** [comment]
To be perfectly honest at first glance this looks like a bug in Chromium's renderer.

**Comment by jplflyer** [comment]
Ah. I don’t know anything about how the internals work. Is there somewhere else I should submit my bug report? Is this part of:

https://www.chromium.org/Home <https://www.chromium.org/Home>

**Comment by lierdakil** [comment]
... anyway, a quick fix is pending in #387; it's not pretty but it works and doesn't seem to break anything else. I'll try to merge and release sooner rather than later.
