### ISSUE TITLE
PDF print for smartphone/tablet/desktop/A4-printer

### ISSUE THREAD

**Issue by kiwi0fruit** [atom-community/markdown-preview-plus#397]
I just put it here as a plan for myself++. When I investigated printing PDF via PhantomeJS it supported setting screen size. So it was possible to PDF-print mobile version of the site. PDF page width was also smaller. And even more: it could print one long-long page (if we never gonna print on paper it's better to have a single page). And with Chrome PDF print cross-references work fine so navigation should be OK. I guess in a headless Chrome/Electron might (but not should) be all such options too. But in order to do so MPP should have css/less theme that adjusts to screen size. I've started changing MPP theme [here](https://github.com/kiwi0fruit/misc/tree/master/mpp). But it's still a long way to go.

So it would be nice to have 4 PDF print options:

* typical phone (single page)
* typical tablet (single page)
* printer (A4 pages)
* desktop (single page)

All this Zoo can even be 7zipped to a single archive that can be 4 times less than 4 files total as 7z reuses it's dictionary.

I guess this can be done via LaTeX better but I'm interested in using Markdown+HTML+MathJax+Chrome stack.

**UPD**

Chrome print doesn't support PDF sidebar TOC. So we are only to navigate via links in a text. To hack this issue a special pandoc filter can be made: it inserts links to the TOC at the top of the document `[≡](#toc)` to every header (yep, the filter should rewrite the TOC too).

**P.S.**

This solution would lack in typography but if implemented would be very robust and fast to (in comparison with LaTeX, maybe).

**UPD**
More [about this problem](https://graphicdesign.stackexchange.com/questions/89439/pdf-design-a-one-size-fits-all-devices-solution).

Multiple documents worry me but I don't know simple solution to this (tags and reflow is brrr...). Though programs like [ZArchiver](https://play.google.com/store/apps/details?id=ru.zdevs.zarchiver&hl=en) for Android, [7-zip](https://www.7-zip.org/) for Windows, [p7zip](https://askubuntu.com/a/369852) for Ubuntu, [The Unarchiver](https://itunes.apple.com/us/app/the-unarchiver/id425424353) for macOS, [IZArc](https://itunes.apple.com/us/app/izarc-extract-files-from-zip-rar-and-7-zip-archives/id526320835) for iOS help use the proposed hackish solution conveniently.

**Comment by kiwi0fruit** [comment]
Chrome print doesn't support PDF sidebar TOC. So we are only to navigate via links in a text. To hack this issue a special pandoc filter can be made: it inserts the link to the TOC at the top of the document: `[≡](#toc)` to every header (yep, the filter should rewrite the TOC too).

P.S. This solution would lack in typography but if implemented would be very robust and fast to (in comparison with LaTeX, maybe..).

**Comment by lierdakil** [comment]
#396 allows setting page size. I'm reluctant to do much else on this subject because the cost of maintenance will skyrocket -- it's, after all, very hard to write useful automated tests for rendering, especially for PDF rendering. And manually testing every version for every possible combination of options is a nightmare I wouldn't wish on anyone.

**Comment by kiwi0fruit** [comment]
If it's related to principles and conscience then it's possible to add this
via plug-in. Or set as permanently experimental feature. Comfort of the
developer is an important thing after all :-)

чт, 31 мая 2018, 8:22 Peter Zagubisalo <peter.zagubisalo@gmail.com>:

**Comment by kiwi0fruit** [comment]
I drop this direction in favor of adding css themes and html templates to https://github.com/jupyter/nbviewer/issues/778
