### ISSUE TITLE
Image scaling issues with non-standard PPI OS settings

### ISSUE THREAD

**Issue by kiwi0fruit** [atom-community/markdown-preview-plus#405]
There is one on Windows when screen scale is set to more than 96 px per inch (for example to 120). May be it's also on Linux - who knows. It's actually a webkit/electron (and other browsers as well) bug.

It happens on images of low resolution. In order to look good their size should not exceed the real size in pixels. Browser keeps their size below the real size... in px. The problem is that the browser's px is larger when scale is larger. So the image is displayed stretched and a bit blurry. I doubt that this would be fixed on browser side (or we can help bring the onset of this event).

For now this can be fixed via setting image size: `![Pic caption](pic/img.png){#fig:1 style="max-height: 400px;"}` where `400px = real_size/1.25` for 1.25 scaled display. I guess this can be automated via js, I even tested [script](https://stackoverflow.com/questions/279749/detecting-the-system-dpi-ppi-from-js-css/35941703#35941703) (and it worked):

```js
function findFirstPositive(b, a, i, c) {
  c=(d,e)=>e>=d?(a=d+(e-d)/2,0<b(a)&&(a==d||0>=b(a-1))?a:0>=b(a)?c(a+1,e):c(d,a-1)):-1
  for (i = 1; 0 >= b(i);) i *= 2
  return c(i / 2, i)|0
}

var dpi = findFirstPositive(x => matchMedia(`(max-resolution: ${x}dpi)`).matches)

console.log(dpi)
```

I plan to fix it in future...

**Comment by lierdakil** [comment]
Not inclined to try to fix UI scaling issues on our end, that way lies madness. At least for now, this is a "wontfix", sorry.

**Comment by kiwi0fruit** [comment]
Unfortunately that's the only place to fix this issue. Dirty hacks are not
madness but a working solutions ;)

>

**Comment by lierdakil** [comment]
Dirty hacks are unmaintainable by definition and we have plenty of those as is. In any case, I don't find the issue of "low-res images looking a bit crap with higher-than-usual PPI settings" to be bad enough to call for drastic measures on our end. Consider complaining on Chromium's bugtracker.

**Comment by lierdakil** [comment]
"Fixing" such issues on the client end is somewhat akin to "fixing" a blown fuse in a house by running an extension cord from a neighbour's power outlet. Works in a pinch, but not a viable long-term solution by any stretch of the imagination.

**Comment by kiwi0fruit** [comment]
I guess your analogy is not correct. It's all about doing things and not doing (and "nobody but us"). But I agree: that's not that awful :)

**Comment by kiwi0fruit** [comment]
I won't fix it either.
