### ISSUE TITLE
Bullet lists displayed wrong in preview (but not in saved HTML)

### ISSUE THREAD

**Issue by Moonbase59** [atom-community/markdown-preview-plus#406]
Using Atom 1.26.1 x64 and markdown-preview-plus 3.3.0, bullet lists having newlines in between list items are (often, not always) shown as a single bullet, the content follows on the next line. If I save the preview as HTML and display it in a browser, all is as expected.

Pleas see attached screenshots.

![bildschirmfoto vom 2018-06-15 12 16 50](https://user-images.githubusercontent.com/3706922/41463441-bd7bad50-7096-11e8-801a-81bcba0be371.png)

![bildschirmfoto vom 2018-06-15 12 17 37](https://user-images.githubusercontent.com/3706922/41463457-d27a6066-7096-11e8-8cd6-e06e7738bfb6.png)

**Comment by Moonbase59** [comment]
Repaired by installing Atom 1.27.2 x64, closing.

**Comment by Moonbase59** [comment]
Unfortunately, it still happens, only not that often.

**Comment by lierdakil** [comment]
This is basically #386. I was pretty sure the last iteration of the fix was working, but apparently not, or at least not always.

I've pushed a very specific fix. Will release as v3.3.1 shortly.

**Comment by Moonbase59** [comment]
»… apparently not always.«

Here’s an example of a bullet list containing a code block that mis-behaves (top right, under »MP3 Diags«);

![bildschirmfoto vom 2018-07-13 15-53-22](https://user-images.githubusercontent.com/3706922/42695321-51b2bc0a-86b5-11e8-818f-f7b28fef11b7.png)

**Comment by lierdakil** [comment]
That's a bug in Chrome apparently. Fixed in Chrome 64, but it will be a while before Electron and Atom update.
