### ISSUE TITLE
Preview doesn't use utf-8 encoding.It uses windows-1252.But the exported page uses uft-8.

### ISSUE THREAD

**Issue by blurHY** [atom-community/markdown-preview-plus#407]
preview
![default](https://user-images.githubusercontent.com/33171396/41507951-37e57e2a-726f-11e8-979b-2af92df956ef.png)
exported

![firefox_2018-06-17_21-07-35](https://user-images.githubusercontent.com/33171396/41508157-a8cf8cfe-7272-11e8-9d57-a73781d84058.png)

**Comment by lierdakil** [comment]
The renderer doesn't seem to care though, does it? After all, `win-1252` doesn't have Chinese characters.
