### ISSUE TITLE
js support?

### ISSUE THREAD

**Issue by blurHY** [atom-community/markdown-preview-plus#409]
![image](https://user-images.githubusercontent.com/33171396/41766379-6a9818f0-7639-11e8-8da4-3345dda73845.png)
The script tag and the attribute 'onclick' is deleted.
Is it possible to add js support?

**Comment by lierdakil** [comment]
No, it is not, since that would be a **huge** security concern.

**Comment by blurHY** [comment]
Add a toggle button in setting pane
![image](https://user-images.githubusercontent.com/33171396/41767505-5966be6c-763c-11e8-9c4c-c297477941ec.png)

**Comment by lierdakil** [comment]
This would still be a huge security concern. Or, let me put it bluntly, a gaping security hole. The preview execution context has access to Node, hence it can do literally anything. You *do not* want to enable arbitrary potentially system-modifying JavaScript execution. Ever.

**Comment by blurHY** [comment]
![image](https://user-images.githubusercontent.com/33171396/41767577-9b7601fa-763c-11e8-8015-510d8d18559a.png)
GFM allows script tag

**Comment by lierdakil** [comment]
<script type="text/javascript">
alert('hello')
</script>
↑ apparently not really, because it's a vulnerability.

Any more questions?

**Comment by blurHY** [comment]
Oh,I see.Thanks for your replies.
