### ISSUE TITLE
Extra newlines in long code blocks

### ISSUE THREAD

**Issue by Moonbase59** [atom-community/markdown-preview-plus#413]
With Atom 1.28.1 (x64) and markdown-preview-plus 3.3.2, I get extra newlines in code block previews that have long lines. See screenshot.

![bildschirmfoto vom 2018-07-13 15-42-29](https://user-images.githubusercontent.com/3706922/42694909-25f9c4e2-86b4-11e8-92ed-8c7bb4bd6210.png)

(I’m using Linux Mint 19.)

**Comment by lierdakil** [comment]
Thanks for reporting. Should be fixed in v3.3.3

**Comment by Moonbase59** [comment]
Thanks for constantly improving it :-) Will check tomorrow.
