### ISSUE TITLE
Syntax Problem

### ISSUE THREAD

**Issue by driftingdream** [atom-community/markdown-preview-plus#414]
Well, like `_test_**test**`, in markdown,it will display fine, like
_test_**test**

However,when you write like this`_test_test**test**`, the former Italic style **doesn't** be applied.
_test_test**test**

But when you write `*test*test**test**`, it displays fine
 *test*test**test**

**However**, you may think it's seldom to be used in English, but when you use it in **Asian** Language, it is **_hard_** to use.

**Comment by lierdakil** [comment]
That's [by design](https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis). You don't ever want to have `something_with_underscores` to get italicized, so spaces are mandatory.

**Comment by driftingdream** [comment]
I forgot the English syntax.... Alright, thanks for answering.
