### ISSUE TITLE
'Flash' on update is distracting

### ISSUE THREAD

**Issue by mangecoeur** [atom-community/markdown-preview-plus#415]
I appreciate the effort that must have gone into the 'flash' over the modified page parts, when actually working it quickly gets very distracting - is it totally necessary?

**Comment by lierdakil** [comment]
It's not the modified parts that flash. It's a side-effect of sync-on-change. Fixing that has been on my to-do list, but I kinda got used to it, so it got pushed aside at some point.

**Comment by lierdakil** [comment]
Should be fixed in v3.3.4.

**Comment by mangecoeur** [comment]
That's awesome thanks!
