### ISSUE TITLE
Not rendering files made before the new update 

### ISSUE THREAD

**Issue by NicklasVraa** [atom-community/markdown-preview-plus#417]
All my markdown files, that I have written **before** the update to 3.3.4 will suddenly **not** render, and instead, toggling the render just closes the file. If I create a new file and copy-paste the contents of the old file, into the new file, the new file **does** render. I have tried reverting back to 3.3.3, but that doesn't help.

**Update**
If I make an arbitrary change to the old files, and save, it will render.

**Comment by lierdakil** [comment]
Uh... No idea. Straight-up closing the file isn't anywhere in the code even. Did you remember to restart Atom after the update?
