### ISSUE TITLE
Previewing Markdown Failed: grammar.tokenizeLines is not a function [Tree Sitter grammars incompatibility]

### ISSUE THREAD

**Issue by linjialiang** [atom-community/markdown-preview-plus#421]
![snipaste_2018-08-21_12-27-58](https://user-images.githubusercontent.com/8848263/44380397-b26ee400-a53d-11e8-939e-4b5984007728.png)

**Comment by lierdakil** [comment]
Nevermind, figured it out. This is an incompatibility with tree-sitter grammars. For now, disable tree-sitter parsers: this option in core settings should be **disabled** (as in picture):
![an empty checkbox next to a caption reading "Use Tree Sitter Parsers"](https://user-images.githubusercontent.com/7275622/44476850-ab30fe80-a641-11e8-8378-0e17c2ea5c31.png)

**Comment by linjialiang** [comment]
thank you
