### ISSUE TITLE
Syntax highlighting interferes with Latex

### ISSUE THREAD

**Issue by iabraham** [atom-community/markdown-preview-plus#427]
The default syntax highlighting for markdown for items within `_` and `*` (italics) and `**` (bold) works great on pure markdown. But it seems to pick up on underscores and asterisks within Latex/Mathjax fenced text also. 

This happens if for example I write `$a _{ij}$` then everything until the next occurrence of `_` gets highlighted as italics. This however does not happen if  instead I write `$a_{ij}$`. Since Tex is agnostic to space it seems there should be a work around for this. 

Similarly, if I write `$k^*$` or `k^{*}` the same thing happens. Is there an option/toggle in settings or work around that will fix this?

**Comment by lierdakil** [comment]
This package doesn't handle syntax highlighting. Try some community packages for Markdown grammar with math support, e.g. https://atom.io/packages/language-markdown
