### ISSUE TITLE
Save as ... PDF output silently produces nothing

### ISSUE THREAD

**Issue by rickhg12hs** [atom-community/markdown-preview-plus#430]
Selecting PDF as the default save option, and then trying `Save as ...`, writes no file (with no complaints either).  `Save as ...` to HTML file seems to work fine.

Is there another step required to generate PDF output? ... or some other dependency?

**Comment by rickhg12hs** [comment]
I randomly selected `Toggle LaTeX Rendering` and now there is a PDF file generated/saved.

1. Wouldn't it be better if the current state of toggles was somehow visible?
2. Regardless of any toggle states, should at least a message to the user let them know why the output requested was not generated?

**Comment by lierdakil** [comment]
This was actually a bug. Which should be fixed in v3.6.2. Thanks for reporting!

> Wouldn't it be better if the current state of toggles was somehow visible?

It's kinda obvious whether math rendering is enabled or not. And it shouldn't really matter if there's no math.

**Comment by rickhg12hs** [comment]
Thanks for fixing it!

**Comment by ginavong** [comment]
Hi, I know this was a few years ago but I'm having the same problem with saving PDF and I can't find the `latex rendering` option. I'm using the default settings with math rendering on if that helps.

**Comment by lierdakil** [comment]
@ginavong should be fixed in v4.9.3. It was a completely unrelated bug. In the future, please open new issues instead of trying to resurrect the ones that were closed for 3 years. Thanks.
