### ISSUE TITLE
3.6.0 introduced some funky rendering issues in table layout

### ISSUE THREAD

**Issue by martimlobao** [atom-community/markdown-preview-plus#431]
Now table lines have a weird double border, and the font changed as well. Here's a basic table in 3.5.0 (top) and 3.6.2 (bottom). Also note that the table size is much larger in 3.6.2.

<img width="407" alt="screen shot 2018-09-11 at 18 39 34" src="https://user-images.githubusercontent.com/6430786/45391769-5524fa80-b5f2-11e8-9053-0989c540b90d.png">
<img width="514" alt="screen shot 2018-09-11 at 18 40 39" src="https://user-images.githubusercontent.com/6430786/45391767-50f8dd00-b5f2-11e8-9ce8-0fc48a5cc1dc.png">

**Comment by lierdakil** [comment]
v3.6.3 should be a bit better wrt cell spacing. Font family really shouldn't change in tables unless you *want* it to (and in that case, feel free to add relevant styles to your user stylesheet under `body > div.update-preview` -- bear in mind those won't work in exported HTML though)

**Comment by martimlobao** [comment]
3.6.3 fixes the double lines on tables, but the default font type is still serif instead of sans serif like it was pre-3.6.0. Is this intentional? The github.com style still uses sans serif text, so I can use that, I guess.

**Comment by lierdakil** [comment]
Sorry for the late response. You can configure arbitrary styles in your stylesheet, for example with like this:
```less
body:not([class]) {
  font-family: "Comic Sans MS";
}
```
(`:not([class])` is there to avoid affecting Atom's primary workspace -- it's not usually all that important when talking about font-family, but a good idea nonetheless; I might add a more specific selector to preview body/html in a later version)
