### ISSUE TITLE
Live Update only works in same window

### ISSUE THREAD

**Issue by michael-mcevoy-morgan6** [atom-community/markdown-preview-plus#434]
I'd like to have my markdown file open on one monitor and my preview open on another. I am currently able to kinda-sorta get that done by opening the *.md file in one window, launching its preview, and then closing the *.md file and opening it in another window. This appears to break Live Update, however.
Is there a supported mechanism for what I'm trying to do?

**Comment by lierdakil** [comment]
Open preview -> context menu -> "Open in new window"; kinda like this https://youtu.be/tBQZDuSslBQ

**Comment by michael-mcevoy-morgan6** [comment]
Oh, man! I had tried that on the tab itself, and didn't see the context menu option. Thanks!
