### ISSUE TITLE
Fonts have been jacked up 3.6.0...3.7.1

### ISSUE THREAD

**Issue by shellscape** [atom-community/markdown-preview-plus#439]
Hey folks. Not sure how to fix this, but the fonts have all reverted to Times New Roman-looking or some such system default font. Sizes and spacing are all wonked. (jacked and wonked are technical terms). Screenshot below of the 3.7.1 CHANGELOG in preview:

![Imgur](https://i.imgur.com/AQQ3qaA.png)

What's the fix for this? (I can't find docs on the fix procedure anywhere.)

**Comment by lierdakil** [comment]
Long story short, 3.6.0 started isolating preview styles from most Atom packages, which also includes theme packages. If you want to revert to old-ish behaviour, set `markdown-preview-plus.importPackageStyles` (called 'Packages that can affect preview rendering' in settings GUI) to `*` (star) to get all Atom stylesheets to affect preview as well. FWIW, this is described in the changelog for v3.6.0.

It is however highly recommended to selectively set styles in your stylesheet instead (Edit -> Stylesheet... menu option). To target the preview body specifically, you can use `body:not([class])` CSS selector, e.g.
```css
body:not([class]) {
  font-family: "Comic Sans MS";
}
```
(note: this will also affect HTML export, but exported HTML can't auto-load any fonts, so use with caution)

**Comment by shellscape** [comment]
thanks @lierdakil. that helped me and hopefully will be useful to someone in the future.

**Comment by kiwi0fruit** [comment]
@lierdakil it's "File -> Stylesheet..." menu option.

**Comment by lierdakil** [comment]
@kiwi0fruit, that might differ between platforms? At least I have that under 'Edit`
![image](https://user-images.githubusercontent.com/7275622/48263471-482c5800-e437-11e8-9704-64fea9fa753f.png)
