### ISSUE TITLE
[Feature Request] Spell checking with languagetool

### ISSUE THREAD

**Issue by mrwunderbar666** [atom-community/markdown-preview-plus#450]
Would be really cool if you could add an interactive spell and grammar checker to the preview pane. Ideally running on a local (offline) installation of languagetool. 

Previous integrations of languagetool into atom have only a mediocre user experience. 

See reference:  https://languagetool.org/

**Comment by lierdakil** [comment]
I *really* don't think adding spellcheck to *preview* is the way to go here. And frankly this is out of scope anyway. So sorry, but the answer's no.
