### ISSUE TITLE
Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method...

### ISSUE THREAD

**Issue by Jont828** [atom-community/markdown-preview-plus#456]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 4.1.4
**OS**: "Arch Linux"
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 3.8.1

### Stack Trace

Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

```
At The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at getGuestInstanceId (/usr/lib/electron/resources/electron.asar/renderer/web-view/web-view.js:241:13)
    at HTMLElement.send (/usr/lib/electron/resources/electron.asar/renderer/web-view/web-view.js:272:77)
    at WebviewHandler.error (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:160:23)
    at MarkdownPreviewViewEditor.showError (/packages/markdown-preview-plus/lib/markdown-preview-view/markdown-preview-view.js:232:22)
    at MarkdownPreviewViewEditor.renderMarkdownText (/packages/markdown-preview-plus/lib/markdown-preview-view/markdown-preview-view.js:220:18)
```

### Commands

```
  2x -0:01.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
atom-react-native-style 0.2.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
city-lights-ui 1.5.3 
color-picker 2.3.0 
docblockr 0.13.7 
editorconfig 2.2.2 
file-icons 2.1.25 
fonts 3.1.0 
Hydrogen 2.5.1 
intentions 1.1.5 
jsx-comment 0.2.0 
language-babel 2.85.0 
language-latex 1.2.0 
language-ocaml 1.9.5 
latex 0.50.2 
latex-completions 0.3.5 
linter 2.2.0 
linter-ui-default 1.7.1 
markdown-pdf 2.2.0 
markdown-preview-plus 3.8.1 
markdown-toc 0.4.2 
markdown-writer 2.11.5 
minimap 4.29.9 
monokai 0.24.0 
monokai-extended 0.3.0 
monokai-flat 1.0.1 
monokai-seti 0.9.0 
multi-cursor 2.1.5 
ocaml-indent 0.6.2 
ocaml-merlin 0.14.5 
open-recent 5.0.0 
pandoc 0.2.2 
pdf-view 0.71.0 
pigments 0.40.2 
prettier-atom 0.55.2 
react 0.18.0 
react-native-snippets 0.3.0 
react-snippets 1.1.1 
seti-syntax 1.2.0 
seti-ui 1.11.0 
space-tab 0.4.2 
spacegray-monokai-ui 2.0.0 
Sublime-Style-Column-Selection 1.7.5 
tab-through 0.7.0 
tabs-to-spaces 1.0.5 
```

**Comment by lierdakil** [comment]
Ouch. Atom apparently updated Electron finally? This might lead to some issues... Thanks for reporting, I'll see what I can figure out.

**Comment by lierdakil** [comment]
Wait. No they didn't? Just installed Atom v1.36.0 and it's still on Electron 2:
$ atom --version
Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

How come you have Electron: 4.1.4 ?

**Comment by Jont828** [comment]
Oh, Atom version gives me the following output. I think it might just be a problem you run into with a rolling release, but I don't seem to be getting that error anymore. Thanks!

```
Atom    : 1.36.0
Electron: 4.1.4
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

**Comment by VP59m** [comment]
I have the same error just now with my arch-based distro! How can I fix?

Atom    : 1.36.1
Electron: 4.1.4
Chrome  : 69.0.3497.128
Node    : 10.11.0

cheers Igor

**Comment by davidlj95** [comment]
Same issue here on an Arch Linux O.S. too

```
Atom    : 1.37.0
Electron: 4.1.4
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

**Comment by lierdakil** [comment]
Atom has just moved to Electron 3.1 with 1.39 release. So I don't know what Arch people are thinking building it against Electron 4.1.4. We can not support that. Your options include: a) using a distro that doesn't try to run in front of the train b) reporting this to Arch maintainers and hoping they fix this on their end c) building Atom yourself d) finding an AUR package that provides an official Atom build.

I'm going to lock this issue, because "me too" reports don't do anyone anything good. If you believe that your case is different from what is described here, feel free to open a new issue. If you can reproduce this on _official_ Atom build, please _do_ open a new issue. Thank you for understanding.
