### ISSUE TITLE
image not showing when image file name have white space

### ISSUE THREAD

**Issue by RupengWang** [atom-community/markdown-preview-plus#459]
<img width="894" alt="屏幕快照 2019-07-10 20 12 57" src="https://user-images.githubusercontent.com/9884693/60968337-64c6ba00-a34f-11e9-9872-47d4410197f1.png">

**Comment by Moonbase59** [comment]
As a workaround, urlencode the image URI, i.e., in your case use `images/fun%202.jpeg` instead.

**Comment by lierdakil** [comment]
This is expected. See https://spec.commonmark.org/0.29/#link-destination

TL;DR: enclose the link in angle brackets, e.g. `![fun2](<images/fun 2.jpeg>)`.

Note that older markdown-it releases did not implement this part of the spec correctly; update to latest markdown-preview-plus to get the latest-and-greatest.
