### ISSUE TITLE
[RFE] Saving state of math rendering?

### ISSUE THREAD

**Issue by cipherboy** [atom-community/markdown-preview-plus#461]
Let's say I have a tree of documents:

```
folder/
 - a.md
 - b.md
 - c.md
```

It'd be lovely for `markdown-preview-plus` to save the state of the math rendering (`ctrl+shift+x`) for each document. Even saving the last state would be nice or a global "enable math mode by default". I find myself looking back at other documents (that aren't necessarily open when I load the editor) and having to switch on math mode for that preview (even when it is enabled in another tab/document preview).

**Comment by lierdakil** [comment]
FWIW, there _is_ a global "enable math mode by default" in the package settings: (go to Atom settings, Packages tab, find markdown-preview-plus, click Settings button)
![image](https://user-images.githubusercontent.com/7275622/63318532-71133f00-c31f-11e9-9e6b-193490d5aac0.png)

Saving state for each document can get somewhat problematic over time, in terms of memory usage. Unless there is a hard limit on the number of documents for which the state is saved that is.

**Comment by cipherboy** [comment]
Well that's awkward, I swear I looked. :D My bad! Yeah, feel free to close this issue.

(I'd personally disagree on the memory usage but with the default-on and the little I use Atom for I don't particularly care.)

Thanks for the awesome plugin!
