### ISSUE TITLE
preview doesn't handle 4 space tabs for lists

### ISSUE THREAD

**Issue by shortda** [atom-community/markdown-preview-plus#462]
With package version 3.9.3 on windows 10, if the markdown code has a list indented with 4 or more spaces then the preview doesn't show a list (list marker and text will be inline with text above). Indenting a list with 1-3 spaces in the markdown code results in a list as expected in the preview.

**Comment by lierdakil** [comment]
This is consistent with [Example 208 of the CommonMark spec](https://spec.commonmark.org/0.29/#example-208). Not a bug.

**Comment by shortda** [comment]
Got it, was looking at the wrong syntax standard. Sorry!

**Comment by lierdakil** [comment]
Actually, wrong example there. The one I should've linked is [Example 282](https://spec.commonmark.org/0.29/#example-282).
