### ISSUE TITLE
Missing Github Emoji SVGs

### ISSUE THREAD

**Issue by janstieler** [atom-community/markdown-preview-plus#463]
Hi,
I use Github markdown and want to use the Github emojis like [here](https://gist.github.com/rxaviers/7360908).
The emojis will also displayed in the markdown preview but I think ist is only the image from the alt-attribute and not the svg because I got the console error `Failed to load resource: net::ERR_FILE_NOT_FOUND – 2757.svg:1`. This is the file who is missing for the Emoji :exclamation:: `.atom/packages/markdown-preview-plus/node_modules/twemoji/dist/svg/2757.svg`

Cheers

**Comment by lierdakil** [comment]
Terribly sorry it took forever to get to this, it kind of slipped through the cracks. Twemoji apparently stopped providing assets with the package at some point for whatever reason. I've released a quick fix as v3.9.4.
