### ISSUE TITLE
Open in New Window fails

### ISSUE THREAD

**Issue by cbourke** [atom-community/markdown-preview-plus#464]
Latest version of atom.io (1.40.1) on a mac using markdown preview plus 3.9.3.  Markdown renders fine in new tab, but when I go right-click "Open in new window" the tab is closed but no new window opens.  Feature worked previously.

**Comment by lierdakil** [comment]
Thanks for reporting! This seems to be an upstream bug, `atom.open` does not work for some reason. I've created an upstream issue.

**Comment by cbourke** [comment]
Thanks for the latest update (v4.0)!  Fantastic re/work/around!  Keep up the great work!

I'll go ahead and close the issue since it is now resolved.  Thanks again!

**Comment by lierdakil** [comment]
Ah, I apparently forgot to announce the feature and close the issue. Glad you've noticed it! Anyway, the feature might be a little undercooked, I've opted to push out something that works sooner rather than later. Feel free to open enhancement requests.
