### ISSUE TITLE
Block math seems to break a list

### ISSUE THREAD

**Issue by AstrickHarren** [atom-community/markdown-preview-plus#473]
I was trying to write a list of math theorems but the displayed math seem to break a list in the middle: if I write

```
1. This is an equation
    $$2x + 3$$
and this line is not in the list. 
```

It looks something like this:

<img width="491" alt="Screen Shot 2019-11-02 at 9 20 37 PM" src="https://user-images.githubusercontent.com/33888523/68071596-c73c3e00-fdb6-11e9-8581-c49c5b5cf4bb.png">

This happens both if I use SVG or HTML-CSS rendering.

**Comment by lierdakil** [comment]
This is expected. Well, kind of. Math parsing with markdown-it is a bit of a hack, and display math is treated as a block-level element. Hence, the `and this line is not in the list` is not a lazy paragraph continuation, but a paragraph in itself. Hence, if you want it to be in the list, you have to indent it by 4 spaces, i.e.
```
1. This is an equation
    $$2x + 3$$
    and this line is now in the list. 
```

**Comment by AstrickHarren** [comment]
Thanks, problem solved. This package really saves a lot of time writing casual math 👍
