### ISSUE TITLE
How to display the number of the code line in the code block

### ISSUE THREAD

**Issue by ZHULOO** [atom-community/markdown-preview-plus#481]
When preview the gfm markdown, it show the code block with no line number, How to display the code line number?  or How to set? Thanks?

**Comment by lierdakil** [comment]
With markdown-it, you don't. And GitHub doesn't do line numbers either, so... 

If you're using [pandoc](https://pandoc.org) (you also need to select it in MPP settings), then see [the docs on fenced code blocks](https://pandoc.org/MANUAL.html#extension-fenced_code_attributes) (TL;DR: add `.numberLines` class). Fair warning: this is non-standard Markdown, and will basically only work with pandoc (which might be fine for your use case, I don't know)

**Comment by ZHULOO** [comment]
Thanks，I will try the `pandoc`.
