### ISSUE TITLE
Support triangle of power in latex

### ISSUE THREAD

**Issue by shaneing** [atom-community/markdown-preview-plus#484]
For example:

$$
\tripow{x}{a+b}{} = \tripow{x}{a}{} \cdot \tripow{x}{b}{}
$$

Then, render it:

<img width="269" alt="Screen Shot 2020-04-22 at 10 14 07 PM" src="https://user-images.githubusercontent.com/14818134/79992910-b4ddca00-84e6-11ea-8d90-1fd95e7aca3d.png">

**Comment by lierdakil** [comment]
AFAIK, this is non-standard LaTeX, so I'm not keen on hard-coding it directly, but we do support global user-defined macros.

TL;DR: you might try to add something like this to your `~/.atom/markdown-preview-plus.cson`:
```cson
dotriangle: [
  "\\hspace{-.2ex}{\\vcenter{#1\\kern.2ex\\hbox{$\\triangle$}\\kern.2ex}}",
  1]
tripow: ["
\\mathop{
 \\mathchoice
    {
       \\vphantom{\\dotriangle\\LARGE}
       \\rule[-1.4ex]{0.1em}{0pt}
       _{\\scriptstyle #1}
       {\\overset{\\scriptstyle #2}
       {\\dotriangle\\LARGE}}
       \\rule[-1.4ex]{0em}{0pt}
       _{\\scriptstyle #3}
       \\rule[0ex]{0.1em}{0pt}
     }
   {
       \\vphantom{\\dotriangle\\normalsize}
       \\rule[-1.05ex]{-0.7ex}{0pt}
       _{#1}
       \\overset{#2}
       {\\dotriangle\\normalsize}
       \\rule[-1.05ex]{0pt}{0pt}
       _{#3}
       \\rule[0ex]{-0.2em}{0pt}
     }
   {
       \\vphantom{\\dotriangle\\normalsize}
       \\rule[-1.05ex]{-0.8ex}{0pt}
       _{\\scriptstyle #1}
       {\\overset{\\scriptstyle #2}
       {\\dotriangle\\normalsize}}
       \\rule[-1.05ex]{0pt}{0pt}
       _{\\scriptstyle #3}
       \\rule[0ex]{-0.3em}{0pt}
    }
   {}
}
", 3]
```
(adapted slightly from https://tex.stackexchange.com/questions/307833/how-to-represent-the-triangle-of-power-in-latex)

See [the docs](https://github.com/atom-community/markdown-preview-plus/blob/master/docs/math.md#macros) for more information on macro definitions in MPP.

**Comment by shaneing** [comment]
@lierdakil Awesome, thanks a lot!
