### ISSUE TITLE
shown nothing

### ISSUE THREAD

**Issue by 914191848** [atom-community/markdown-preview-plus#489]
win10，atom + markdown-preview-plus shown nothing。。。

![2020-05-27_2-32-33](https://user-images.githubusercontent.com/30688308/82937904-88284100-9fc3-11ea-8326-f5cbc9eb410c.jpg)

**Comment by lierdakil** [comment]
See https://github.com/atom-community/markdown-preview-plus/issues/487

TL;DR: upstream broke most preview-type packages on Atom 1.47. Downgrade to 1.46 for the time being. 1.48 should be fine once it comes out.

**Comment by 914191848** [comment]
thanks, the problem have been solved
