### ISSUE TITLE
Preview remains empty on macOS Catalina

### ISSUE THREAD

**Issue by mlangiu** [atom-community/markdown-preview-plus#494]
Hi, thanks for this useful package!

Unfortunately after a while of working fine, MPP suddenly shows strange behavior for me:

The Keybindings are still resolved as:
```
'atom-text-editor, webview.markdown-preview-plus':
  'ctrl-shift-M': 'markdown-preview-plus:toggle'

'atom-text-editor, webview.markdown-preview-plus':
  'ctrl-shift-X': 'markdown-preview-plus:toggle-render-latex'
```
but the preview tab that opens when pressing them is empty (just shows a black or white background depending on the syntax theme used).
I get the same behavior trying to toggle it via the command palette and regardless of the backend I select.

I'm on a Mac running Catalina, on an older Mac running Sierra things were similar but a reinstall of MPP resolved the issue, not so on Catalina (I tried uninstalling and reinstalling from within Atom and via apm).

Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

<details>
<summary>Installed Packages</summary>

Built-in Atom Packages (93)
├── atom-dark-syntax@0.29.1
├── atom-dark-ui@0.53.3
├── atom-light-syntax@0.29.1
├── atom-light-ui@0.46.3
├── base16-tomorrow-dark-theme@1.6.0
├── base16-tomorrow-light-theme@1.6.0
├── one-dark-ui@1.12.5
├── one-light-ui@1.12.5
├── one-dark-syntax@1.8.4
├── one-light-syntax@1.8.4
├── solarized-dark-syntax@1.3.0
├── solarized-light-syntax@1.3.0
├── about@1.9.1
├── archive-view@0.65.2
├── autocomplete-atom-api@0.10.7
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.8
├── autocomplete-plus@2.42.3
├── autocomplete-snippets@1.12.1
├── autoflow@0.29.4
├── autosave@0.24.6
├── background-tips@0.28.0
├── bookmarks@0.46.0
├── bracket-matcher@0.91.2
├── command-palette@0.43.5
├── dalek@0.2.2
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.9
├── exception-reporting@0.43.1
├── find-and-replace@0.219.3
├── fuzzy-finder@1.14.2
├── github@0.34.2-3
├── git-diff@1.3.9
├── go-to-line@0.33.0
├── grammar-selector@0.50.1
├── image-view@0.64.0
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.39.0
├── line-ending-selector@0.7.7
├── link@0.31.6
├── markdown-preview@0.160.2 (disabled)
├── metrics@1.8.1
├── notifications@0.71.0
├── open-on-github@1.3.2
├── package-generator@1.3.0
├── settings-view@0.261.4
├── snippets@1.5.1
├── spell-check@0.76.1 (disabled)
├── status-bar@1.8.17
├── styleguide@0.49.12
├── symbols-view@0.118.4
├── tabs@0.110.0
├── timecop@0.36.2
├── tree-view@0.228.0
├── update-package-dependencies@0.13.1
├── welcome@0.36.9
├── whitespace@0.37.7
├── wrap-guide@0.41.0
├── language-c@0.60.19
├── language-clojure@0.22.8
├── language-coffee-script@0.50.0
├── language-csharp@1.1.0
├── language-css@0.44.4
├── language-gfm@0.90.7
├── language-git@0.19.1
├── language-go@0.47.2
├── language-html@0.53.1
├── language-hyperlink@0.17.1
├── language-java@0.31.4
├── language-javascript@0.134.1
├── language-json@1.0.5
├── language-less@0.34.3
├── language-make@0.23.0
├── language-mustache@0.14.5
├── language-objective-c@0.16.0
├── language-perl@0.38.1
├── language-php@0.44.4
├── language-property-list@0.9.1
├── language-python@0.53.4
├── language-ruby@0.72.23
├── language-ruby-on-rails@0.25.3
├── language-rust-bundled@0.1.0
├── language-sass@0.62.1
├── language-shellscript@0.28.2
├── language-source@0.9.0
├── language-sql@0.25.10
├── language-text@0.7.4
├── language-todo@0.29.4
├── language-toml@0.20.0
├── language-typescript@0.6.2
├── language-xml@0.35.3
└── language-yaml@0.32.0

Community Packages (32) /Users/marcolangiu/.atom/packages
├── Hydrogen@2.14.4
├── atom-ide-debugger-python@0.7.3
├── atom-ide-ui@0.13.0
├── atom-latex@0.9.1
├── autocomplete-python@1.16.0
├── build@0.70.0
├── busy-signal@2.0.1
├── file-icons@2.1.41
├── hydrogen-launcher@1.2.2
├── hydrogen-python@0.0.8
├── ide-python@1.5.0
├── intentions@1.1.5
├── language-ampl-syntax@1.2.0
├── language-cmake@1.2.0
├── language-gams@0.6.0
├── language-ini@1.23.0
├── language-latex@1.2.0
├── linter@2.3.1 (disabled)
├── linter-spell@0.15.0
├── linter-spell-latex@0.11.0
├── linter-ui-default@1.8.1
├── markdown-preview-plus@3.11.5
├── minimap@4.29.9
├── package-sync@1.1.0
├── pdf-view@0.72.0
├── python-debugger@0.2.0
├── python-tools@0.6.9
├── scroll-editor-on-middle-click@0.7.0
├── split-diff@1.6.1
├── symbols-navigator@1.9.0
├── sync-settings@4.3.5
└── wordnet@0.2.0
<\details>

**Comment by jmound** [comment]
I'm seeing the same behavior as well.

**Comment by mlangiu** [comment]
Hmm, I can't really explain what happened, but after some more trial and error I reinstalled Atom using homebrew (`brew cask install --appdir="/Applications" atom`) and now things are working as normal!

**Comment by lierdakil** [comment]
Hi. You've apparently hit https://github.com/atom-community/markdown-preview-plus/issues/487. Atom v1.46 and v1.48 are unaffected, so homebrew probably updated to v1.48.
