### ISSUE TITLE
Latex command documentation link is outdated

### ISSUE THREAD

**Issue by jooseyo** [atom-community/markdown-preview-plus#505]
Hi,

In features, [Supported LaTeX commands](http://docs.mathjax.org/en/latest/tex.html#supported-latex-commands) is outdated. Also, for macros of Latex, the file to be edited is `~/.atom/markdown-preview-plus.yaml` not `~/.atom/markdown-preview-plus.cson`. I think the documentation must be updated.

Also, is there a way to include any Latex packages? or, do you have plan to add it?

**Comment by lierdakil** [comment]
Yep, docs need to be updated. Apparently I forgot to do it. The correct link is http://docs.mathjax.org/en/v2.7-latest/tex.html#supported-latex-commands (at least for the time being we're sticking to MathJax v2.7)

> Also, is there a way to include any Latex packages? or, do you have plan to add it?

Not possible and no plan. We aren't actually using LaTeX, we're using MathJax. It's a rather limited subset of LaTeX math specifically, so supporting bona fide LaTeX packages is simply not possible. You want full-blown LaTeX, you use full-blown LaTeX.
