### ISSUE TITLE
Support MetaWebLog API.

### ISSUE THREAD

**Issue by kingreatwill** [atom-community/markdown-preview-plus#506]
Like this.
![image](https://user-images.githubusercontent.com/13087689/93287982-71755680-f80d-11ea-9686-2d34e62a0b2a.png)

**Comment by lierdakil** [comment]
This seems entirely out of scope to me, I don't see how a preview package would be related to web publishing. Besides, MetaWebLog is outdated beyond belief -- the current W3C recommendation is Micropub. One could also perhaps use RFC 5023.

Feel free to write a new package that would handle publishing. If you really want to tie it to MPP I would be happy to discuss the  API required for interoperability. I won't personally implement support for an unrelated task using an outdated standard I never used and don't plan to.
