### ISSUE TITLE
4.8.4 Bring up preview when editor activates doesn't seem to work

### ISSUE THREAD

**Issue by bentwookie** [atom-community/markdown-preview-plus#513]
Atom 1.53.0
markdown-preview-plus 4.8.4
Windows 10 (2004)
No other packages installed

I'm trying to make it so I can simply double click on an .md file in File Explorer and it previews in Atom. I have markdown-preview-plus installed, the core markdown package disabled and the 'Bring up preview when editor activates' checkbox checked. When I open an .md file from File Explorer (or even within Atom itself), the file opens as raw markdown and doesn't preview. Control-shift-M previews fine.

**Comment by lierdakil** [comment]
'Bring up preview when editor activates' isn't supposed to open the preview automatically, it only "activates" the preview if it's already open (i.e. focuses the preview tab in a non-active pane). Perhaps the wording on the option is confusing, and needs to be amended somewhat. Feel free to offer suggestions.

If you want to auto-open previews, you might be interested in [markdown-preview-plus-opener](https://atom.io/packages/markdown-preview-plus-opener).

**Comment by bentwookie** [comment]
Got it. Thanks!
