### ISSUE TITLE
MPP Tembles

### ISSUE THREAD

**Issue by BrunoGoirand** [atom-community/markdown-preview-plus#515]
[MPP-Shakes.mov.zip](https://github.com/atom-community/markdown-preview-plus/files/5707992/MPP-Shakes.mov.zip)

Hello,
The attachment shows the behavior. 
It is a 6 seconds video that shows what happens when I scroll the markdown text up and down.
The preview shakes, trembles.
It is very difficult to scroll, the text always gets back to its initial position.
When insisting on the scroll key, it ends up to scroll but the preview never gets stabilised. It always trembles.
Is there a specific parameter to fix this behavior ?
Thank you

**Comment by lierdakil** [comment]
If you could attach your Atom config (the part that is related to MPP at least) that would be very helpful. Also, the Atom version might be relevant. Thanks.

**Comment by lierdakil** [comment]
Also, as a quick sanity check, post the list of packages you have installed (run `apm list --enabled` in terminal and paste output here). This might be due to interference from a different package.

**Comment by BrunoGoirand** [comment]
Hi,

<img width="306" alt="Screenshot 2020-12-20 at 10 57 00" src="https://user-images.githubusercontent.com/35697301/102710645-0461d900-42b4-11eb-8d4c-fec17d159fe6.png">

[atom_enabled.txt](https://github.com/atom-community/markdown-preview-plus/files/5720764/atom_enabled.txt)

[Archive.zip](https://github.com/atom-community/markdown-preview-plus/files/5720769/Archive.zip)

I hope you will find all you need here attached.
I removed all packages, uninstalled MPP, re-installed it, left all settings as default.

I just observed that the markdown preview only shakes when there are both the md file and the preview on screen at the same time. It seems that the shakes is linked to the synchro between the two windows.
When I scroll the preview and the md file is not showed (for example the left pane could be atom settings instead), it does not shakes. The md preview works well.

**Comment by lierdakil** [comment]
Okay, I was able to reproduce thanks to your config. This seemingly happens only when the preview is opened in the dock, and not when it's in the main screen. I have an idea of why this might be happening. Will get back to you shortly, hopefully with a fix. As a band-aid, you might want to switch MPP to open in the main area, i.e. with something like
![image](https://user-images.githubusercontent.com/7275622/102715449-9e427980-42e6-11eb-837d-13068293ebd6.png)

**Comment by lierdakil** [comment]
Okay, published v4.9.0 which should fix this unfortunate issue. Thanks for reporting!

**Comment by BrunoGoirand** [comment]
Hi,
You welcome. It is TOP that you could reproduce it. It was kind of difficult to explain!
Thank you very much for fixing.
Your workaround is working, even if this doesn't seem to be perfect perfect.
Waiting for 4.9.0 to definitely fix this.

**Comment by lierdakil** [comment]
You shouldn't actually need to wait. Just open Atom settings, go to Updates tab, and MPP update should show up.
