### ISSUE TITLE
Save as PDF produces nothing

### ISSUE THREAD

**Issue by ginavong** [atom-community/markdown-preview-plus#522]
Save as PDF takes you through the "save as" menu but silently produces no file. Print to PDF still works but hyperlinks etc won't work this way.

# Info
System info: Windows 10, MPP 4.9.4 default settings
Started: Sometime in April after an update (there have been many updates recently and I can't remember which one sorry).

## Steps to reproduce
1. Create and input text into a .md file.
2. View preview.
3. Right click on preview and select 'save as' 
![image](https://user-images.githubusercontent.com/77932267/116699160-29322f80-a9bd-11eb-8bf7-18a275228eac.png)

4. Change filename to name.pdf
5. Select save
6. Go to file location.
7. No file exists.

**Comment by lierdakil** [comment]
This was an issue with Atom 1.56 (more specifically Electron 9), but I'm pretty sure I fixed it in v4.9.4. That said, I didn't test on Windows, this may be platform-specific. I personally use pdf export occasionally, and it works for me in v4.9.5 and Atom v1.56. Just to be sure, check if the issue reproduces on latest releases. Meanwhile, I'll try to get a dev environment up and running on some Windows machine.

**Comment by lierdakil** [comment]
Can't reproduce on Windows 10, Atom v1.56.0, MPP v4.9.5.

**Comment by ginavong** [comment]
Confirmed: it works on MPP v4.9.5 thanks
