### ISSUE TITLE
TypeError: Cannot read property 'nativePageScrollKeys' of undefined

### ISSUE THREAD

**Issue by Maccha-Azuki** [atom-community/markdown-preview-plus#525]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 4.11.0

### Stack Trace

TypeError: Cannot read property 'nativePageScrollKeys' of undefined

```
At Cannot read property 'nativePageScrollKeys' of undefined

TypeError: Cannot read property 'nativePageScrollKeys' of undefined
    at /packages/markdown-preview-plus/dist/main.js:1:218581
```

### Commands

```
```

### Non-Core Packages

```
markdown-image-paste 2.5.2 
markdown-img-paste 0.4.0 
markdown-preview-plus 4.11.0 
pp-markdown 0.0.2 
simplified-chinese-menu 5.3.5 
```

**Comment by lierdakil** [comment]
Hello!

Can't reproduce, and it shouldn't really ever happen unless Atom got the packages into an inconsistent state (like unloaded the package config before unloading the package itself or somesuch). Generally, Atom restart and/or package reinstallation fixes such issues.
