### ISSUE TITLE
Support for passing in a `--defaults` file to pandoc

### ISSUE THREAD

**Issue by pbsds** [atom-community/markdown-preview-plus#531]
I request the ability to set a custom (`defaults.yaml`)[https://pandoc.org/MANUAL.html#default-files], much like how it is possible to set custom bibfiles and cslfiles which are searched for recursively.

With this addition, the preview could adapt to each project instead of having to configure settings such as filters globally.
This change will also partially sidestep #530

**Comment by lierdakil** [comment]
Hi. Sorry for the late response. It's a good call, but I'm currently very short on spare time, so resolving it might take a while. In the meantime, I can suggest a workaround. You can actually pass arbitrary arguments to pandoc. The option's in the settings. Pandoc is executed from the file's directory, which theoretically would allow you to pass `--defaults defaults.yaml` globally and just plop the defaults file next to the markdown file itself. I understand this is not a great option, but atm it's either this or nothing, I'm afraid.

**Comment by pbsds** [comment]
I totally glossed over that option. Thanks.
