### ISSUE TITLE
Pandoc PDF rendering

### ISSUE THREAD

**Issue by leipert** [atom-community/markdown-preview-plus#57]
If pandoc is enabled, we should support a `render PDF with pandoc` on rightclick option.

Relates to #34

**Comment by cavaunpeu** [comment]
would this allow me to export/save to pdf?

**Comment by leipert** [comment]
If you have pandoc installed and latex on your PC, as pandoc uses latex for pdf rendering, you should be able to save it as pdf, but this feature is not implemented yet.

**Comment by zweicoder** [comment]
@leipert what is the exact line you use to get the formatting right? I'm using `pandoc -o test.pdf -s test.md -f markdown-raw_tex+tex_math_single_backslash` and it doesn't work properly
