### ISSUE TITLE
Extract specs from atom/markdown-preview-plus issues

### ISSUE THREAD

**Issue by leipert** [atom-community/markdown-preview-plus#85]
The default markdown-preview holds a lot of issues with valuable specs.

Read them, steal them, check them ;)

**Comment by Galadirith** [comment]
> Read them, steal them, check them ;)

Should that not be the package `description`? :D (only half joking)

**Comment by leipert** [comment]
Just worked through 150 Issues. Rest to come :+1:

**Comment by leipert** [comment]
I finished reading all the issues and extracting the good ones for us. Just have to compile them nicely.
