### ISSUE TITLE
Links to local or network paths (file:///)

### ISSUE THREAD

**Issue by jonand** [atom-community/markdown-preview-plus#87]
This issue is possibly related to issue [#72](https://github.com/Galadirith/markdown-preview-plus/issues/72).

I often use markdown to keep track of various file paths, local and network windows paths. With my regular Pandoc workflow this works when using the file:/// prefix and when opening the links from within internet explorer. Chrome doesn't allow linking to local or network paths and opening the paths in explorer.

The markdown-preview-plus preview in atom doesn't allow me to open file:/// links. Possibly because Chrome doesn't allow this? Is it possible to fix?

**Comment by leipert** [comment]
How do you want to open the links? Within atom or in their native Program like Word?

With #72 we are working on opening files within atom.
I think we will not support opening `file:///` links with other programs than atom.

We will definitely have a look into opening file:/// links once we are working on #72

**Comment by jonand** [comment]
I'd like the links to open in native programs, e.g. windows explorer for paths or internet explorer for .html.

**Comment by leipert** [comment]
Okay, I will have a look into it, but I do not know whether we can do it.

**Comment by lierdakil** [comment]
Relevant: #303
